Fix C++20 KOKKOS_LAMBDA deprecation warning
kokkos/kokkos pull request #2494
Opened 2019-10-22 19:19 UTC by masterleinad

Fixes #2454. `KOKKOS_CLASS_LAMBDA` should be used instead of `KOKKOS_LAMBDA` in places where `this` is implicitly captured. Unfortunately, we can only do this for `C++17` and later. To be able to write code that both avoids this warning for C++17 and later and still works for C++14 and below, this pull requests defines `KOKKOS_CLASS_LAMBDA` the same as `KOKKOS_LAMBDA` as this is the closest we can (easily) get.

2019-10-23 14:38 UTC, dalg24 requested changes

2019-10-23 14:38 UTC, dalg24 commented on core/unit_test/TestRange.hpp
>                a(i)++;
This won't work pre C++17.  You need to do something like
```C++
auto that = *this;
Kokkos::parallel_for(policy_t(0, N), KOKKOS_LAMBDA(int i) {
  ...
  that.a(i)++;
  ...
});
```

2019-10-25 03:27 UTC, dalg24 approved these changes

2019-10-25 03:28 UTC, merged

2019-10-26 19:43 UTC, crtrott commented
Uhm: I don't think this is ok. This obfuscates the issue that people are not allowed to capture the this pointer ever inside of a dispatch operation, because it violates Kokkos semantics.

2019-10-27 00:46 UTC, dalg24 commented
Proposed alternative fix is 8f66f19