[WIP] Require C++14
kokkos/kokkos pull request #3281
Opened 2020-08-13 18:32 UTC by masterleinad

Still needs #3278 and the minimum compilers supported need to be updated, too.

2020-08-14 13:49 UTC, Rombur commented on example/tutorial/03_simple_view_lambda/CMakeLists.txt
> +  COMM serial mpi
The `COMM` line is not necessary because the tutorial does not use MPI and somehow this trips the tester.

2020-08-14 20:55 UTC, masterleinad commented
Retest this please.

2020-08-17 19:20 UTC, Rombur requested changes

2020-08-17 19:20 UTC, Rombur commented on cmake/README.md
> +target_compile_options(A PUBLIC -std=c++14)
This is not correct. You need to update the whole section.

2020-08-17 19:20 UTC, Rombur commented on cmake/kokkos_test_cxx_std.cmake
> +# works.  Both NVCC and nvcc_wrapper only recognize '-std=c++14' which means
You missed a `C++11` a couple of lines above and a `gnu++11` a couple lines below.

2020-08-17 19:58 UTC, Rombur approved these changes

2020-08-26 17:44 UTC, masterleinad commented
Retest this please.

2020-08-26 20:01 UTC, dhollman approved these changes

2020-09-02 15:30 UTC, merged