Allow to override build date with SOURCE_DATE_EPOCH
kokkos/kokkos pull request #3327
Opened 2020-08-29 01:46 UTC by bmwiedemann

Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible (of the `trilinos` package).
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.

This date call is designed to work with all variants of date.

Also use UTC to be independent of timezone.

As an alternative, the date could be dropped to reduce complexity.

This PR was done while working on reproducible builds for openSUSE.

2020-08-31 17:04 UTC, masterleinad commented
@bmwiedemann Note that our build system is `CMake` base and the Makefile should only be used in rare cases.

2020-09-01 05:38 UTC, bmwiedemann commented
It seems, trilinos is using the Makefile.

2020-09-02 02:51 UTC, bmwiedemann commented
Added a comment to `Makefile.kokkos`

2020-09-02 16:03 UTC, crtrott commented
Note Trilinos has not been using the Makefile.kokkos since January.

2020-09-02 16:05 UTC, crtrott commented
Also we do not support installing Kokkos via Makefile.kokkos, which means the only thing you can do with the Makefile is building an app directly with Kokkos as an inline build, is that a scenario where you care about this?

2020-09-09 16:05 UTC, crtrott commented
@bmwiedemann considering this doesn't affect Trilinos do you still care?

2020-09-09 16:49 UTC, bmwiedemann commented
It did affect trilinos and they dont want to change the code because it is coming from kokkos. So not sure how to continue there.

2020-09-10 17:40 UTC, masterleinad commented
@bmwiedemann If you care, you can of course propose a change to the `CMake` files instead according to the `CMake` section in https://reproducible-builds.org/docs/source-date-epoch/.

2020-09-11 22:06 UTC, crtrott commented
So if there is actually a problem in Trilinos this won't fix it, and we don't add a date in a cmake build. I think I rather drop the date in the Makefile.kokkos based build too.

2020-09-16 04:16 UTC, crtrott requested changes
Suggest we just drop the build date line 452.

2020-09-16 04:16 UTC, crtrott commented
I blocked it with a change request, we will assign someone.

2020-09-16 19:21 UTC, janciesko commented
Is superseded by PR #3392

2020-09-16 21:21 UTC, closed without merging