replace cuda enabled check with cuda active execution memory space check
kokkos/kokkos pull request #3349
Opened 2020-09-08 16:15 UTC by jeffmiles63

Cuda atomics are only relevant within the active cuda execution memory

2020-09-08 19:32 UTC, masterleinad reviewed
AFAICT, `KOKKOS_ENABLE_CUDA_ATOMICS` is mostly unused.
```
$ git grep -n "KOKKOS_ENABLE_CUDA_ATOMICS" | grep "def" | grep "if"
core/src/Kokkos_Atomic.hpp:154:#if defined(KOKKOS_ENABLE_CUDA_ATOMICS)
core/src/impl/Kokkos_Core.cpp:1056:#ifdef KOKKOS_ENABLE_CUDA_ATOMICS
```
 We rather use
```
#if defined(KOKKOS_ENABLE_CUDA)
#if defined(__CUDA_ARCH__) || defined(KOKKOS_IMPL_CUDA_CLANG_WORKAROUND)
```
to guard device code.

In the two results above, the macro is only used in host functions so the current behavior is probably what we want even though it doesn't match the comment.

2020-09-11 21:53 UTC, crtrott commented
I am not so sure about this change because of clang. Remember that functions decalarations need to match in host and device compilation. This is likely the reason why we changed some of the stuff as Daniel discussed above. I would rather not mess with it since it actually could lead to us hitting the fallback atomic implementation via locks without us noticing.

2020-09-11 21:54 UTC, crtrott requested changes
See my comment, feeling a bit uneasy about this, and if we did anything like this we need to run a lot of tests on whether we are hitting the correct atomic implementation and not just the fallback implementation for both Clang and NVCC as the compiler. If the change is not strictly needed for anything I would rather drop it.

2020-09-14 20:34 UTC, jeffmiles63 commented
I just ran the tests with this change removed, and it doesn't not appear to make a difference.  closing pull request as a result

2020-09-14 20:34 UTC, closed without merging