Fence active instead of default execution space instances
kokkos/kokkos pull request #3388
Opened 2020-09-15 20:14 UTC by masterleinad

Related to https://github.com/kokkos/kokkos/pull/3364/files#r485331579.
This should catch all cases where an execution space instance is available but we fence the default one instead.

2020-09-15 20:26 UTC, crtrott requested changes
Actually the bounds checking is funky. Shouldn't the check be after the fence? But yeah otherwise this looks good.

2020-09-15 20:58 UTC, masterleinad commented
> Actually the bounds checking is funky. Shouldn't the check be after the fence? But yeah otherwise this looks good.

I think this is correct. We first check for invalid launch arguments via `cudaGetLastError`, then force the host to wait until the kernel stops and then check for an execution error.

2020-09-16 03:19 UTC, crtrott approved these changes

2020-09-16 03:21 UTC, crtrott submitted a review, later dismissed
Actually we might wanna resolve with this the changes in #3363

2020-09-24 18:49 UTC, dalg24 approved these changes
I rebased on develop

2020-09-25 03:36 UTC, merged