Use bool for enums representing bools
kokkos/kokkos pull request #3416
Opened 2020-09-24 14:29 UTC by masterleinad

This avoids some implicit conversions that would be detected by some static analyzers.

2020-09-24 15:32 UTC, crtrott requested changes
I want this tested with more compilers than are in the CI @ndellingwood we had issues before with stuff like this.

2020-09-29 18:11 UTC, masterleinad commented
@ndellingwood Would you mind checking if this works for the larger amount of compilers we are testing?

2020-09-29 21:27 UTC, ndellingwood commented
@masterleinad I launched tests with intel compilers (17, 18, 19) and subset of configurations, let me know if we need additional compilers checked as well.

2020-09-29 22:05 UTC, ndellingwood commented
Intel spot-check results from kokkos-dev pass (I cherry-picked f1dfdcfeb655fe8e54107dc150fedbd76e3cf632 to add intel 18 and 19 testing options)

```bash
Running on machine: kokkos-dev
Repository Status:  f1dfdcfeb655fe8e54107dc150fedbd76e3cf632 update testing scripts for kokkos-dev


Going to test compilers:  intel/17.0.1 intel/18.0.5 intel/19.0.5
Testing compiler intel/17.0.1
Testing compiler intel/18.0.5
  Starting job intel-17.0.1-OpenMP-release
kokkos options: 
kokkos devices: OpenMP
kokkos cxx: -O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-17.0.1-OpenMP-release
Testing compiler intel/19.0.5
  Starting job intel-18.0.5-Serial-release
kokkos options: 
kokkos devices: Serial
kokkos cxx: -O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-18.0.5-Serial-release
  Starting job intel-19.0.5-Pthread_Serial-release
kokkos options: 
kokkos devices: Pthread,Serial
kokkos cxx: -O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized 
  PASSED intel-19.0.5-Pthread_Serial-release
#######################################################
PASSED TESTS
#######################################################
intel-17.0.1-OpenMP-release build_time=205 run_time=232
intel-18.0.5-Serial-release build_time=166 run_time=326
intel-19.0.5-Pthread_Serial-release build_time=311 run_time=967
```

2020-09-30 02:57 UTC, masterleinad commented
Retest this please.

2020-09-30 04:09 UTC, crtrott approved these changes
ok

2020-09-30 04:09 UTC, merged