Avoid rewriting test files when calling cmake
kokkos/kokkos pull request #3548
Opened 2020-10-30 17:06 UTC by masterleinad

Previously, we were changing the timestamp of the generated test files every time we called `cmake` resulting in unnecessary rebuilds. `configure_file` only changes the files if they differ.

2020-10-31 01:11 UTC, masterleinad commented
Retest this please.

2020-10-31 02:43 UTC, masterleinad commented
Retest this please.

2020-10-31 21:13 UTC, masterleinad commented
Retest this please.

2020-11-02 15:15 UTC, masterleinad commented
Retest this please.

2020-11-02 16:53 UTC, dalg24 requested changes
Please comment that you are writing a temporary intermediate file and calling `configure_file` to avoid updating timestamps which would trigger unnecessary rebuilds on subsequent cmake runs.

2020-11-02 17:28 UTC, masterleinad commented
> Please comment that you are writing a temporary intermediate file and calling `configure_file` to avoid updating timestamps which would trigger unnecessary rebuilds on subsequent cmake runs.

See [`8aedb69` (#3548)](https://github.com/kokkos/kokkos/pull/3548/commits/8aedb6953a98fc80073e995f9d66b794270b2019).

2020-11-02 20:01 UTC, jjwilke requested changes
I can approve without the suggested change - but curious what you think.

2020-11-02 20:01 UTC, jjwilke commented on core/unit_test/CMakeLists.txt
> +      configure_file(${dir}/dummy.cpp ${file})
Would it be better to have a dummy.cpp.in with @TEST@, etc and skip the first `file(WRITE`?

2020-11-03 13:50 UTC, dalg24 requested changes
Your last commit invalidates the comments.  You must fix it.

I do not like your implementation of the changes suggested by @jjwilke.  One now has to open `test.cpp.in` to understand what is going on and nothing in the name of the variables indicates that they are being substituted in the file being configured.
My preference goes to revert.

2020-11-03 13:54 UTC, masterleinad commented
I don't really care one way or the other. @dalg24 seems to feel more strongly than @jjwilke so I'll just revert.

2020-11-03 14:18 UTC, masterleinad commented
Retest this please.

2020-11-03 18:16 UTC, dalg24 approved these changes

2020-11-03 20:35 UTC, jjwilke approved these changes
Yep, I'm not going fight on this one : )

2020-11-04 03:34 UTC, merged