Fix xl issues
kokkos/kokkos pull request #3637
Opened 2020-12-01 22:20 UTC by crtrott

This fixes a few issues in builds using IBM XL. It splits an test object file into two files, and it moves another object file to a different executable. All the failing tests did fail when run with gtest filter, i.e. failure didn't depend on other tests being run first. The explicitly added cpp files are there, since the UVM and HostPinned test cpp files are NOT autogenerated in our system yet.

2020-12-01 22:33 UTC, dalg24 requested changes
Fix the indentation in the Makefile

2020-12-01 22:33 UTC, dalg24 commented on core/unit_test/Makefile
> +        OBJ_HIP += TestHIPHostPinned_ViewCopy_a.o TestHIPHostPinned_ViewCopy_b.o
Fix indentation here and below

2020-12-01 22:33 UTC, dalg24 commented on core/unit_test/TestViewCopy_b.hpp
> +}  // namespace
This code is being duplicated in `TestViewCopy_{a,b}.hpp`

2020-12-01 22:33 UTC, dalg24 commented on core/unit_test/CMakeLists.txt
> +      hip/TestHIPHostPinned_ViewCopy_b.cpp
Too bad we are not generating these files yet

2020-12-03 15:52 UTC, masterleinad approved these changes
Looks OK to me.

2020-12-03 16:09 UTC, dalg24 approved these changes

2020-12-03 16:14 UTC, merged