Avoid using sudo cmake in GitHub CI
kokkos/kokkos pull request #3686
Opened 2020-12-22 14:48 UTC by masterleinad

We don't install `cmake` in a folder `sudo` can use anymore so just use `sudo make` instead of messing with `/etc/sudoers` in the container.

2020-12-22 14:56 UTC, dalg24 commented
> We don't install `cmake` in a folder `sudo` can use anymore so just use `sudo make` instead of messing with `/etc/sudoers` in the container.

What does "a folder `sudo` can use" mean?

2020-12-22 14:59 UTC, masterleinad commented
> What does "a folder `sudo` can use" mean?

`/opt` is not in `secure_path` which is used as `PATH` variable when using `sudo` (https://askubuntu.com/a/924048).

2020-12-22 15:09 UTC, masterleinad commented
Another alternative would of course be to revert installing our own CMake in the containers (after discussing that we probably rather want to enforce 3.16 instead of 3.17).

2020-12-22 15:14 UTC, dalg24 commented
Or just install in `/usr/local`

2020-12-22 15:15 UTC, dalg24 commented
Also why do you need to install with `sudo` in the first place?

2020-12-22 15:21 UTC, masterleinad commented
> Also why do you need to install with `sudo` in the first place?

We are installing into `/usr` in this step. (I would also be fine dropping this step).

2020-12-22 15:24 UTC, masterleinad commented
> Or just install in `/usr/local`

Yes, also possible. I didn't want to mess with the paths managed by the system too much but it shouldn't really matter. 

I have a slight preference for fixing it here in some way instead of messing with the containers again.

2020-12-22 16:33 UTC, DavidPoliakoff approved these changes
Discussed in Slack. Works around oddities of the environment

2020-12-22 17:38 UTC, dalg24 requested changes
Install elsewhere and don't use sudo

2020-12-22 17:44 UTC, masterleinad commented
> Install elsewhere and don't use sudo

I simply dropped the last step since we are already installing in the previous one.

2020-12-22 18:51 UTC, dalg24 commented
@junghans please review

2020-12-22 20:21 UTC, junghans commented
> > Install elsewhere and don't use sudo
> 
> I simply dropped the last step since we are already installing in the previous one.

Nope the previous step is to check if something gets installed outside of the `/usr` prefix using `DESTDIR`. At the end everything gets removed. In some way that tests in the installation works, too, but we should really test install kokkos for real.

2020-12-22 20:22 UTC, junghans requested changes
Just install cmake in `/usr/local` and leave things here as they are.

2020-12-22 20:46 UTC, masterleinad commented
> Just install cmake in `/usr/local` and leave things here as they are.

See https://github.com/kokkos/ci-containers/pull/5.

2020-12-22 20:54 UTC, masterleinad commented
>  In some way that tests in the installation works, too, but we should really test install kokkos for real.

So what are we actually testing in this last step? We only copy files but don't check whether the installed version is functional.

2020-12-23 16:11 UTC, DavidPoliakoff commented
I think the right move is to merge this, and improve it later as necessary. Right now it shuts down our CI completely

2020-12-23 16:35 UTC, junghans commented
> I think the right move is to merge this, and improve it later as necessary. Right now it shuts down our CI completely

Hopefully we can merge https://github.com/kokkos/ci-containers/pull/5 in a sec.

2020-12-23 16:38 UTC, junghans commented
> > In some way that tests in the installation works, too, but we should really test install kokkos for real.
> 
> So what are we actually testing in this last step? We only copy files but don't check whether the installed version is functional.

We test if the install actually. My plan was to ultimately deploy the container, but have implement that yet.

2020-12-23 16:41 UTC, junghans commented
> > > In some way that tests in the installation works, too, but we should really test install kokkos for real.
> > 
> > 
> > So what are we actually testing in this last step? We only copy files but don't check whether the installed version is functional.
> 
> We test if the install actually. My plan was to ultimately deploy the container, but have implement that yet.

You raise a good point, in Cabana we test if the install actually works: https://github.com/ECP-copa/Cabana/blob/d46804f0e002be4d9f7740fc94a34c4ff1fe6aa3/.travis.yml#L108-L111

Is there a simple example in kokkos we could compile afterwards, too?

2020-12-23 16:45 UTC, dalg24 commented
cc @janciesko and @Rombur 

> Is there a simple example in kokkos we could compile afterwards, too?

We are looking into enabling building examples/tutorials from the main repo against an installed Kokkos.
Something along the lines of https://github.com/arborx/ArborX/blob/5380818f651ede3bc679f182990508e99e338e0e/examples/CMakeLists.txt#L1-L6

2020-12-23 16:49 UTC, junghans commented
> cc @janciesko and @Rombur
> 
> > Is there a simple example in kokkos we could compile afterwards, too?
> 
> We are looking into enabling building examples/tutorials from the main repo against an installed Kokkos.
> Something along the lines of https://github.com/arborx/ArborX/blob/5380818f651ede3bc679f182990508e99e338e0e/examples/CMakeLists.txt#L1-L6

Yeah in Cabana we do:
https://github.com/ECP-copa/Cabana/blob/master/example/tutorial/01_hello_world/CMakeLists.txt#L3-L7
this would assume that the target is alias to the namespaced target, i.e. `kokkos` is aliased to `Kokkos::kokkos`.

2020-12-23 17:00 UTC, junghans commented
New kokkos ci image got published, so this PR was be closed.

2020-12-28 17:02 UTC, closed without merging