Add fast-math to known NVCC flags
kokkos/kokkos pull request #3699
Opened 2021-01-04 20:45 UTC by arghdos

2021-01-04 20:46 UTC, arghdos commented
Very minor change we made to support testing of LAMMPS w/ fast-math enabled on NV.  If it doesn't fit or isn't desired, feel free to close.

2021-01-04 21:39 UTC, dalg24 requested changes
Please make the destination branch `master -> develop`

2021-01-04 21:54 UTC, masterleinad reviewed
Since we already have `--fmad`, adding `--use_fast_math` looks reasonable to me.

2021-01-05 03:17 UTC, crtrott approved these changes

2021-01-05 03:17 UTC, merged