Eliminate sycl_indirect_launch
kokkos/kokkos pull request #3777
Opened 2021-02-03 22:20 UTC by masterleinad

We can avoid the indirection through `sycl_indirect_launch` if we just wrap the functor appropriately to have a container that 
1. can store the `unique_ptr` if necessary and
2. can return the functor we want to forward to `sycl_direct_launch`

This avoids us writing the same code for `sycl_indirect_launch` all the time.

2021-02-05 19:57 UTC, masterleinad commented
Retest this please.

2021-02-09 01:10 UTC, nliber approved these changes

2021-02-09 21:45 UTC, dalg24 approved these changes
I am not a big fan of `(*(m_policy.space()).impl_internal_space_instance()).m_indirectKernelMem` but looks good other than that.

2021-02-09 21:46 UTC, dalg24 requested changes
Clean up history and I will merge

2021-02-09 22:54 UTC, dalg24 approved these changes
When you decide on squashing everything you can tell me and I can do it when I merge

2021-02-09 23:00 UTC, masterleinad commented
> When you decide on squashing everything you can tell me and I can do it when I merge

Sure.

2021-02-10 02:32 UTC, merged