Migrate dockerfiles to use cmake apt repo
kokkos/kokkos pull request #4049
Opened 2021-05-25 14:54 UTC by masterleinad

Cherry-picked from https://github.com/kokkos/kokkos/pull/3913. Given that we constantly running into problems downloading `CMake`, I at least want to discuss the approach of using the `apt` repository provided by `CMake` instead.

2021-05-25 15:24 UTC, masterleinad commented
Retest this please.

2021-05-26 14:00 UTC, masterleinad commented
Retest this please.

2021-05-26 14:58 UTC, masterleinad commented
Retest this please.

2021-05-26 15:29 UTC, masterleinad commented
Retest this please.

2021-05-26 18:19 UTC, masterleinad commented
Retest this please.

2021-06-02 14:37 UTC, crtrott approved these changes
Seems fine to me but put on the list for todays discussion.

2021-06-03 14:33 UTC, dalg24 requested changes
I like our being able to specify exactly what version of CMake we want.
We would lose that ability with the changes suggested here.

How often does retrieving the GPG keys from the server fail?  They are alternative solution if this is has actually become an issue.
https://github.com/arborx/ArborX/blob/13d7ef8aeea37d6bff3425d6bd9c4cf4d77fa056/docker/Dockerfile#L26-L32

2021-06-03 14:51 UTC, masterleinad commented
> How often does retrieving the GPG keys from the server fail?

In my experience, it fails a couple of times whenever we need to rebuild an image which happens without any changes to the Dockerfiles multiple times per week (since we are cleaning up images to avoid running out-of-memory). I'm very much in favor of a solution so that we don't need to request a rebuild in particular if only one build fails because of this.

2021-06-03 15:04 UTC, dalg24 commented on scripts/docker/Dockerfile.clang
> +    apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(cat /etc/lsb-release | grep DISTRIB_CODENAME | awk -F '=' '{print $NF}') main" && \
there is no need to `cat` the file
`grep DISTRIB_CODENAME /etc/lsb-release | cut -d= -f2` does what you want

2021-06-03 15:06 UTC, dalg24 commented
@masterleinad Do you see any issue with the solution I suggested (get key from a keydump hosted on our server)

2021-06-03 15:13 UTC, masterleinad commented
No, not really. I can give it a shot.

2021-06-03 17:50 UTC, masterleinad commented
Closing in favor of #4066.

2021-06-03 17:50 UTC, closed without merging