Swap x- and y-indices in SYCL TeamPolicy
kokkos/kokkos pull request #4166
Opened 2021-07-15 16:32 UTC by masterleinad

Analogous to #4161, this pull request swaps the order of blocks and threads also for `TeamPolicy`. Since `vector_size==1` at the moment, this should not make any difference with respect to performance. In case we want to continue using a 2-dimensional `sycl::nd_range`, this is the way to go, though.

2021-07-15 21:11 UTC, crtrott requested changes

2021-07-15 21:11 UTC, crtrott commented on core/src/SYCL/Kokkos_SYCL_Parallel_Team.hpp
> +              sycl::range<2>(m_vector_size, m_team_size)),
that doesn't make sense, the vector needs to be on the right most side or? Vector threads need to be closest.

So I was thinking:
```
sycl::range<2>(m_team_size, m_league_size * m_vector_size),
sycl::range<2>(m_team_size, m_vector_size))
```

2021-07-15 21:40 UTC, masterleinad commented
The corresponding code for the `CUDA` backend is https://github.com/kokkos/kokkos/blob/35ae5dc71bdb1ce85c3102279b13bb4d5e8771e3/core/src/Cuda/Kokkos_Cuda_Parallel.hpp#L760-L761
so for swapping x- and y- in comparison, we need
```
 sycl::nd_range<2>(
              sycl::range<2>(m_team_size, m_league_size * m_vector_size),
              sycl::range<2>(m_team_size, m_vector_size))
```

2021-07-15 23:39 UTC, crtrott approved these changes

2021-07-20 13:11 UTC, dalg24 approved these changes

2021-07-20 13:11 UTC, merged