Deprecate TeamPolicy::vector_length_max() and TeamPolicy::verify_requested_vector_length()
kokkos/kokkos pull request #4186
Opened 2021-07-26 21:58 UTC by masterleinad

`TeamPolicy::vector_length_max` can not be static for `SYCL`, see https://github.com/kokkos/kokkos/pull/4183#discussion_r676609718. In an attempt to work around this, this pull request provides the same functionality as `TeamPolicy::vector_length_max()` and `TeamPolicy::verify_requested_vector_length()` in TeamPolicy::vector_size_max()` and `TeamPolicy::verify_requested_vector_size()` as non-static member functions.

Of course, I'm open to other solutions.

2021-07-27 20:15 UTC, masterleinad commented
Retest this please.

2021-07-28 13:37 UTC, masterleinad commented
Retest this please.

2021-07-28 18:28 UTC, DavidPoliakoff commented
Preliminary Vote (implement this as a non-static instance method with a different name)
SF F N A SA
1 1 8 2 0

No consensus

2021-07-30 18:27 UTC, crtrott commented
I am strongly against for now. There are some good reasons for this property to be a static property of the backend.

2021-07-30 18:27 UTC, crtrott requested changes
There is no consensus for this change I am blocking this for now.

2021-07-30 18:36 UTC, masterleinad commented
> I am strongly against for now. There are some good reasons for this property to be a static property of the backend.

So how would we do this for `SYCL` where we can initialize execution spaces from `sycl::queue`s that might be associated to a device that is different from the default one?

AFAICT, `vector_length_max` is rarely used. Internally, there is only one use within `Tuning` that can be easily replaced and the only occurrence in `Trilinos` seems to use it as a member variable already.
What are the reasons for keeping this static (apart from the pain associated with deprecating and replacing the name)?

2021-07-30 20:40 UTC, crtrott commented
For example we use that outside of Trilinos in conjunction with SIMD classes, which need to know a compile time size.

2021-12-16 17:36 UTC, crtrott commented
I guess we need to discuss this more.

2022-03-16 18:50 UTC, closed without merging