Enforce allowing large ranges for SYCL
kokkos/kokkos pull request #4211
Opened 2021-08-03 21:24 UTC by masterleinad

Fixes https://github.com/kokkos/kokkos/issues/4210. We need to set `-fno-sycl-id-queries-fit-in-int` to make sure that we can't ranges exceeding MAX_INT, see https://software.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/offload-compilation-options-openmp-options-and-parallel-processing-options/fsycl-id-queries-fit-in-int.html.

2021-08-03 21:42 UTC, crtrott commented
Is that actually supposed to make this work? If yes we should enable the 5B long run in TestView_64bit.hpp (currently it reduces the range to 1B for SYCL).

2021-08-03 22:32 UTC, masterleinad commented
> Is that actually supposed to make this work? If yes we should enable the 5B long run in TestView_64bit.hpp (currently it reduces the range to 1B for SYCL).

No, I still get
```
PI CUDA ERROR:
	Value:           1
	Name:            CUDA_ERROR_INVALID_VALUE
	Description:     invalid argument
	Function:        cuda_piEnqueueKernelLaunch
	Source Location: /scratch/llvm/sycl/plugins/cuda/pi_cuda.cpp:2465
```

for the first test. Note that the others use larger ranges already, though, and work on `Intel GPUs`.
AFAICT, we never run this test in our CI anyway, i.e. I couldn't find a build with `Kokkos_ENABLE_LARGE_MEM_TESTS=On`.

2021-08-03 22:33 UTC, masterleinad commented
Retest this please.

2021-08-04 14:17 UTC, dalg24 commented
Retest this please

2021-08-04 17:04 UTC, masterleinad commented
It seems that some more problems even on Intel GPUs and I pushed some fixes and workarounds for that. I also opened an issue upstream, see https://github.com/intel/llvm/issues/4255.

2021-08-19 23:47 UTC, nliber approved these changes

2021-09-01 14:35 UTC, crtrott requested changes
Almost good, just one question.

2021-09-01 14:35 UTC, crtrott commented on core/src/SYCL/Kokkos_SYCL_Parallel_Reduce.hpp
> +    const size_t nwork = m_policy.m_num_tiles;
should this be Policy::index_type?

2021-09-03 18:42 UTC, crtrott approved these changes

2021-09-03 18:42 UTC, merged