Enable deprecated code in Makefile builds
kokkos/kokkos pull request #4215
Opened 2021-08-04 01:42 UTC by crtrott

2021-08-04 01:43 UTC, crtrott commented
We could consider adding a proper configure option ...

2021-08-04 12:04 UTC, dalg24 commented on Makefile.kokkos
> +tmp := $(call kokkos_append_header,"$H""define KOKKOS_ENABLE_DEPRECATED_CODE_3")
How would one enable using the generated makefiles?

2021-08-04 13:43 UTC, masterleinad reviewed
IMHO it's OK to enable it unconditionally for Makefile builds (since this is also the default for `CMake` builds).
What's your thought on `KOKKOS_ENABLE_DEPRECATION_WARNINGS`? The default for `CMake` builds would also be to emit deprecation warnings.

2021-08-05 23:21 UTC, crtrott commented
OK I added the options to the Makefile now, with deprecated code ON by default and warnings OFF by default.

2021-08-06 13:26 UTC, masterleinad approved these changes
Looks OK to me.

2021-08-06 14:50 UTC, dalg24 requested changes

2021-08-06 14:50 UTC, dalg24 commented on Makefile.kokkos
> +# Options: aggressive_vectorization,disable_profiling,enable_large_mem_tests,disable_complex_align,disable_deprecated_code,enable_deprecation_warning
```suggestion
# Options: aggressive_vectorization,disable_profiling,enable_large_mem_tests,disable_complex_align,disable_deprecated_code,enable_deprecation_warnings
```
to be consistent with the CMake options

2021-08-06 14:50 UTC, dalg24 commented on Makefile.kokkos
> +  tmp := $(call kokkos_append_header,"$H""define KOKKOS_ENABLE_DEPRECATION_WRANINGS")
```suggestion
  tmp := $(call kokkos_append_header,"$H""define KOKKOS_ENABLE_DEPRECATION_WARNINGS")
```

2021-08-06 15:01 UTC, crtrott commented on Makefile.kokkos
> +# Options: aggressive_vectorization,disable_profiling,enable_large_mem_tests,disable_complex_align,disable_deprecated_code,enable_deprecation_warning
done

2021-08-06 15:01 UTC, crtrott commented on Makefile.kokkos
> +  tmp := $(call kokkos_append_header,"$H""define KOKKOS_ENABLE_DEPRECATION_WRANINGS")
done

2021-08-06 15:07 UTC, dalg24 approved these changes

2021-08-06 16:39 UTC, merged