[HIP] Fix issue w/ static initialization of function attributes
kokkos/kokkos pull request #4242
Opened 2021-08-16 18:25 UTC by arghdos

Fix issue w/ static initialization of function attributes on unspecialized type and add test.

This was a fun one to debug.  Basically, on line 214 (https://github.com/kokkos/kokkos/compare/develop...arghdos:fix_launch_mechs?expand=1#diff-078df6e850082d467d9c91f0888ce3b7b5f5f0fcde51bc91a00845ec6dd9bfb0R214), we use a static initialization of the function attributes to "cache" them.  However, this means that we will only get the function attributes for first kernel function pointer passed in.  This means that on subsequent calls we will get (e.g.,) incorrect `localSizeBytes`, which results in an incorrect launch bound determination at runtime.

2021-08-16 18:48 UTC, masterleinad approved these changes
Looks reasonable to me.

2021-08-16 20:50 UTC, dalg24 requested changes
Looks good, except the name of the alias that is bad.  Please change it.

2021-08-16 20:50 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
> +  using base_t = HIPParallelLaunchKernelFuncData<
`base_t` is misleading, it is not the base class that `HIPParallelLaunchKernelFunc` derives from.

2021-08-16 20:59 UTC, dalg24 commented
By the way I'd swear we ran into that exact same kind of bug in the past

2021-08-16 21:02 UTC, dalg24 commented
> By the way I'd swear we ran into that exact same kind of bug in the past

Yup #3712

For the record this one was introduced in #3820

2021-08-16 22:07 UTC, dalg24 approved these changes

2021-08-17 10:19 UTC, Rombur approved these changes

2021-08-17 12:37 UTC, merged