adding KOKKOS_FORCEINLINE_FUNCTION to constbitset constructors
kokkos/kokkos pull request #4296
Opened 2021-09-03 22:39 UTC by matt-stack

Adding KOKKOS_FORCEDINLINE_FUNCTION to the ConstBitset constructors to allow for use on device and to match the bitset. Used in https://github.com/kokkos/kokkos/pull/4135

2021-09-03 22:40 UTC, matt-stack commented
And to operator=

2021-09-04 15:24 UTC, crtrott approved these changes

2021-09-06 21:52 UTC, crtrott commented
OK to test.

2021-09-07 14:08 UTC, dalg24 requested changes
Why `KOKKOS_FORCEINLINE_FUNCTION` and not just `KOKKOS_FUNCTION`?

2021-09-07 15:39 UTC, matt-stack commented
@dalg24 I was looking to keep consistent between constbitset and bitset, and bitset had defined their copy constructors as inline, so I wanted to use define as inline, and figured to force the inline for optimization. But I have no strong opinion as long as __device__ is in the macros somewhere ;) Would you rather me change it to use KOKKOS_FUNCTION or KOKKOS_INLINE_FUNCTION? I understand the argument that it might not be best to force inline and risk breaking someones code

2021-09-07 15:55 UTC, dalg24 commented
Please use `KOKKOS_FUNCTION`

2021-09-07 18:02 UTC, dalg24 approved these changes

2021-09-07 19:09 UTC, merged