Replace deprecated sycl::ONEAPI namespace w/ sycl::ext::oneapi
kokkos/kokkos pull request #4370
Opened 2021-09-29 15:37 UTC by joeatodd

`sycl::ONEAPI` doesn't exist on the tip of the `sycl` branch, it's been replaced with `sycl::ext::oneapi`.

2021-09-29 15:57 UTC, masterleinad requested changes
Most of the changes here are already contained in https://github.com/kokkos/kokkos/pull/4244/commits/3c526432246a4480e85bf23eb0934297800e5b4b. I thought about splitting that pull request anyway so I'm fine with updating it here.

Apart from the typo, this looks good to me.

2021-09-29 15:57 UTC, masterleinad commented on core/src/desul/atomics/Macros.hpp
> +#elseg
```suggestion
#else
```

2021-09-30 13:20 UTC, masterleinad commented
On second thought, this will probably not pass CI since the compiler version is too old. Maybe we just rebase after #4244.

2021-09-30 14:51 UTC, dalg24 commented
> On second thought, this will probably not pass CI since the compiler version is too old. Maybe we just rebase after #4244.

I don't understand.  I thought all changes proposed here are included in #4244

2021-09-30 14:57 UTC, masterleinad commented
> I don't understand. I thought all changes proposed here are included in #4244

Yes, I think so. There are slight differences (`sycl::ext::oneapi::atomic_fence` instead of `sycl::atomic_fence`) but this pull request should be superseded by #4244.

2021-09-30 14:59 UTC, dalg24 commented
So close it?

2021-09-30 15:09 UTC, masterleinad commented
Let's ask first. @joeatodd does #4244 work for you as a replacement for this one?

2021-10-01 08:46 UTC, joeatodd commented
yes, superseded by #4244

2021-10-01 08:46 UTC, closed without merging