Allow Kokkos::create_mirror* to be used with WithoutInitializing
kokkos/kokkos pull request #4486
Opened 2021-10-29 21:07 UTC by masterleinad

Fixes https://github.com/kokkos/kokkos/issues/4259.

2021-11-01 14:37 UTC, masterleinad commented
With
```C++
int main(int argc, char* argv[]) {
  Kokkos::initialize(argc, argv);
  {
    Kokkos::View<int*, Kokkos::Experimental::SYCLDeviceUSMSpace> device_view("device view", 10);
    Kokkos::View<int*, Kokkos::HostSpace> host_view("host view", 10);

    auto mirror_device = Kokkos::create_mirror(device_view);
    auto mirror_host = Kokkos::create_mirror(Kokkos::Experimental::SYCLDeviceUSMSpace{}, host_view);
    auto mirror_device_view = Kokkos::create_mirror_view(device_view);
    auto mirror_host_view = Kokkos::create_mirror_view(Kokkos::Experimental::SYCLDeviceUSMSpace{}, host_view);
  }
  {
    Kokkos::View<int*, Kokkos::Experimental::SYCLDeviceUSMSpace> device_view("device view", 10);
    Kokkos::View<int*, Kokkos::HostSpace> host_view("host view", 10);

    auto mirror_device_wi = Kokkos::create_mirror(Kokkos::WithoutInitializing, device_view);
    auto mirror_host_wi = Kokkos::create_mirror(Kokkos::WithoutInitializing, Kokkos::Experimental::SYCLDeviceUSMSpace{}, host_view);
    auto mirror_device_view_wi = Kokkos::create_mirror(Kokkos::WithoutInitializing, device_view);
    auto mirror_host_view_wi = Kokkos::create_mirror(Kokkos::WithoutInitializing, Kokkos::Experimental::SYCLDeviceUSMSpace{}, host_view);
  }
  Kokkos::finalize();
}
```
I am getting
```
KokkosP: Example Library Initialized (sequence is 0, version: 20210623)
KokkosP: Allocate<SYCLDeviceUSM> name: device view pointer: 0x2970a80 size: 40
KokkosP: Executing parallel-for kernel on device 117440513 with unique execution identifier 0
KokkosP: Kokkos::View::initialization [device view] via memset
KokkosP: Execution of kernel 0 is completed.
KokkosP: Allocate<Host> name: host view pointer: 0x2926180 size: 40
KokkosP: Executing parallel-for kernel on device 1 with unique execution identifier 1
KokkosP: Kokkos::View::initialization [host view] via memset
KokkosP: Execution of kernel 1 is completed.
KokkosP: Allocate<Host> name: device view_mirror pointer: 0x2972780 size: 40
KokkosP: Executing parallel-for kernel on device 1 with unique execution identifier 2
KokkosP: Kokkos::View::initialization [device view_mirror] via memset
KokkosP: Execution of kernel 2 is completed.
KokkosP: Allocate<SYCLDeviceUSM> name: host view pointer: 0x2972f00 size: 40
KokkosP: Executing parallel-for kernel on device 117440513 with unique execution identifier 3
KokkosP: Kokkos::View::initialization [host view] via memset
KokkosP: Execution of kernel 3 is completed.
KokkosP: Allocate<Host> name: device view_mirror pointer: 0x2973e40 size: 40
KokkosP: Executing parallel-for kernel on device 1 with unique execution identifier 4
KokkosP: Kokkos::View::initialization [device view_mirror] via memset
KokkosP: Execution of kernel 4 is completed.
KokkosP: Allocate<SYCLDeviceUSM> name: host view pointer: 0x2974600 size: 40
KokkosP: Executing parallel-for kernel on device 117440513 with unique execution identifier 5
KokkosP: Kokkos::View::initialization [host view] via memset
KokkosP: Execution of kernel 5 is completed.
KokkosP: Deallocate<SYCLDeviceUSM> name: ceUSM pointer: 0x2974600 size: 40
KokkosP: Deallocate<Host> name: device view_mirror pointer: 0x2973e40 size: 40
KokkosP: Deallocate<SYCLDeviceUSM> name: ceUSM pointer: 0x2972f00 size: 40
KokkosP: Deallocate<Host> name: device view_mirror pointer: 0x2972780 size: 40
KokkosP: Deallocate<Host> name: host view pointer: 0x2926180 size: 40
KokkosP: Deallocate<SYCLDeviceUSM> name: ceUSM pointer: 0x2970a80 size: 40
KokkosP: Kokkos library finalization called.
```
for the overloads without `WithoutInitializing` and
```
KokkosP: Example Library Initialized (sequence is 0, version: 20210623)
KokkosP: Allocate<SYCLDeviceUSM> name: device view pointer: 0x1ef2180 size: 40
KokkosP: Executing parallel-for kernel on device 117440513 with unique execution identifier 0
KokkosP: Kokkos::View::initialization [device view] via memset
KokkosP: Execution of kernel 0 is completed.
KokkosP: Allocate<Host> name: host view pointer: 0x1e9bb40 size: 40
KokkosP: Executing parallel-for kernel on device 1 with unique execution identifier 1
KokkosP: Kokkos::View::initialization [host view] via memset
KokkosP: Execution of kernel 1 is completed.
KokkosP: Allocate<Host> name: device view_mirror pointer: 0x1ef3bc0 size: 40
KokkosP: Allocate<SYCLDeviceUSM> name: host view pointer: 0x1ef4300 size: 40
KokkosP: Allocate<Host> name: device view_mirror pointer: 0x1ef4cc0 size: 40
KokkosP: Allocate<SYCLDeviceUSM> name: host view pointer: 0x1ef5400 size: 40
KokkosP: Deallocate<SYCLDeviceUSM> name: ceUSM pointer: 0x1ef5400 size: 40
KokkosP: Deallocate<Host> name: device view_mirror pointer: 0x1ef4cc0 size: 40
KokkosP: Deallocate<SYCLDeviceUSM> name: ceUSM pointer: 0x1ef4300 size: 40
KokkosP: Deallocate<Host> name: device view_mirror pointer: 0x1ef3bc0 size: 40
KokkosP: Deallocate<Host> name: host view pointer: 0x1e9bb40 size: 40
KokkosP: Deallocate<SYCLDeviceUSM> name: ceUSM pointer: 0x1ef2180 size: 40
KokkosP: Kokkos library finalization called.
```
with `WithoutInitializing`. We should add a test like this once we have #4331.

2021-11-08 22:20 UTC, masterleinad commented
I added a test after we merged #4331. This only fixes some issues when including the basic testing include files.

2021-11-09 22:47 UTC, masterleinad commented
Retest this please.

2021-11-24 18:46 UTC, janciesko reviewed
LGTM

2021-11-24 19:12 UTC, janciesko approved these changes

2021-11-26 20:55 UTC, rgayatri23 approved these changes

2021-11-29 15:42 UTC, crtrott requested changes
Are we introducing all kinds of overloads with unconstrained additional arguments here? If so shouldn't those be functions in the Impl namespace?

2021-11-29 17:52 UTC, masterleinad commented
> Are we introducing all kinds of overloads with unconstrained additional arguments here? If so shouldn't those be functions in the Impl namespace?

All the overloads with unconstrained arguments (for `WithouutInitializing` and other view properties) are in namespace `Impl` already.

2021-11-29 19:20 UTC, crtrott approved these changes
Ah saw the namespace stuff now.

2021-11-29 19:20 UTC, merged