Add checks for shmem usage in parallel_reduce
kokkos/kokkos pull request #4548
Opened 2021-11-22 15:57 UTC by ldh4

This is to resolve #4461 

For CUDA build, the problem comes from ParallelReduce where it determines the necessary scratch space size and the block size for the reduced view. Starting from the size of 181 doubles for the reduced view, the calculated block size drops from 32 to 16, which seems to cause cuda illegal memory access. Interestingly, for ParallelReduce that takes in a teampolicy, there already is a similar check that uses the teamsize instead of the block size to verify the similar condition. So, to keep the conditions of the throws as consistently as possible across the policies, this commit puts in a simple function that checks if the calculated block size would be set below 32 because of the internal max shared memory size per block.

For HIP build, starting from 125 doubles, the calculated block size drops to 0. And there already is a check in HIP::ParallelReduce that throws if the calculated block size becomes 0, which is what was observed in the original issue post.

2021-11-30 17:54 UTC, crtrott requested changes
Can we make the test a general test for all backends? I.e. does this work with HIP/SYCL (do they have implemented array reductions actually?)

2021-11-30 17:56 UTC, masterleinad commented
> Can we make the test a general test for all backends? I.e. does this work with HIP/SYCL (do they have implemented array reductions actually?)

Array reductions are implemented for `HIP` and `SYCL`.

2021-11-30 18:21 UTC, ldh4 commented
> Can we make the test a general test for all backends? I.e. does this work with HIP/SYCL (do they have implemented array reductions actually?)

I only looked into the existing array reduction size limits in `CUDA` and `HIP`, but if there's a similar shared memory limits for array reduction in `SYCL` as well, the test can be converted to a general test. Each backend will just need to be checking against different shared memory limit in that case.
I'll also add in a bit more expressive way of calculating the shared memory limit in the test so that the general test won't just be checking against some magical number hard-coded per backend.

2021-12-02 00:27 UTC, crtrott commented
I am not sure that there is a completely generic way of figuring out max shmem size. We would probably need to do a function you hand the execution space instance, and then overloads for that in the test where you in fact use semi magic numbers, or low level backend specific functions to figure it out (i.e. call raw CUDA/HIP/SYCL functionality)

2022-01-24 20:21 UTC, ajpowelsnl commented
Please fix:

```
/var/jenkins/workspace/Kokkos/core/unit_test/cuda/TestCuda_ReducerViewSizeLimit.cpp:59:3: error: use 'using' instead of 'typedef' [modernize-use-using,-warnings-as-errors]

  typedef ValueType value_type[];

  ^

/var/jenkins/workspace/Kokkos/core/unit_test/cuda/TestCuda_ReducerViewSizeLimit.cpp:100:3: error: use 'using' instead of 'typedef' [modernize-use-using,-warnings-as-errors]

  typedef ValueType value_type[];

  ^
```

2022-01-27 01:30 UTC, ldh4 commented
@crtrott, as we discussed before, I will open another issue to convert this Cuda unit-test to a general test for other backends once this is merged.

2022-01-27 22:21 UTC, crtrott approved these changes

2022-01-28 16:52 UTC, merged