Use two-pass SYCL reduction
kokkos/kokkos pull request #4554
Opened 2021-11-24 17:29 UTC by masterleinad

This pull request makes the SYCL reduction algorithm more similar to the one used for CUDA and HIP by atomically counting the number of groups that have completed their reduction and performing the final reduction using the last group. This avoids launching multiple kernels. We still need to evaluate if the performance is better for typical cases we care about.

2021-11-30 15:53 UTC, crtrott approved these changes

2021-12-01 17:49 UTC, masterleinad commented
Retest this please.

2021-12-08 22:31 UTC, masterleinad commented
This should work now. Performance-wise, I am seeing with the previous (recursive) reduction
```
n = 128
DOT KK: 8.125400e-02 s 2.347390e-02 GB/s
DOT SYCL: 1.958490e-01 s 9.738873e-03 GB/s
n = 1024
DOT KK: 1.484400e-01 s 1.027943e-01 GB/s
DOT SYCL: 2.367506e-01 s 6.445091e-02 GB/s
n = 8192
DOT KK: 1.152356e-01 s 1.059311e+00 GB/s
DOT SYCL: 2.786170e-01 s 4.381295e-01 GB/s
n = 65536
DOT KK: 1.376041e-01 s 7.096901e+00 GB/s
DOT SYCL: 3.195702e-01 s 3.055862e+00 GB/s
n = 524288
DOT KK: 1.546102e-01 s 5.053030e+01 GB/s
DOT SYCL: 3.673366e-01 s 2.126796e+01 GB/s
n = 4194304
DOT KK: 2.397862e-01 s 2.606488e+02 GB/s
DOT SYCL: 5.326571e-01 s 1.173363e+02 GB/s
n = 33554432
DOT KK: 1.000666e+00 s 4.996672e+02 GB/s
DOT SYCL: 1.517351e+00 s 3.295217e+02 GB/s
```
and with the new one
```
n = 128
DOT KK: 9.855819e-02 s 1.935251e-02 GB/s
DOT SYCL: 2.032535e-01 s 9.384086e-03 GB/s
n = 1024
DOT KK: 9.871241e-02 s 1.545782e-01 GB/s
DOT SYCL: 2.491157e-01 s 6.125181e-02 GB/s
n = 8192
DOT KK: 1.067829e-01 s 1.143163e+00 GB/s
DOT SYCL: 2.872575e-01 s 4.249508e-01 GB/s
n = 65536
DOT KK: 1.524431e-01 s 6.406078e+00 GB/s
DOT SYCL: 3.313814e-01 s 2.946944e+00 GB/s
n = 524288
DOT KK: 1.648413e-01 s 4.739408e+01 GB/s
DOT SYCL: 3.883306e-01 s 2.011817e+01 GB/s
n = 4194304
DOT KK: 2.785022e-01 s 2.244148e+02 GB/s
DOT SYCL: 5.026499e-01 s 1.243410e+02 GB/s
n = 33554432
DOT KK: 1.428359e+00 s 3.500520e+02 GB/s
DOT SYCL: 1.492831e+00 s 3.349340e+02 GB/s
```
on a V100 which is pretty inconclusive.

2021-12-15 01:36 UTC, nliber requested changes

2021-12-15 01:36 UTC, nliber commented on core/src/SYCL/Kokkos_SYCL_Parallel_Reduce.hpp
> +                  for (unsigned int id = local_id + wgroup_size; id < n_wgroups;
These really should be `size_t`, not `unsigned int`.

2022-01-06 14:31 UTC, masterleinad commented
Superseded by #4608.

2022-01-06 14:31 UTC, closed without merging