Fix 4401
kokkos/kokkos pull request #4605
Opened 2021-12-10 20:15 UTC by crtrott

Adds a more rigorous test for View.span/extent/extent_int and fixes LayoutStride rank-0 span() value

2021-12-10 20:16 UTC, crtrott commented
Fixes #4401

2021-12-16 16:20 UTC, dalg24 requested changes

2021-12-16 16:35 UTC, fnrizzi approved these changes

2021-12-16 16:41 UTC, crtrott commented on core/src/impl/Kokkos_ViewMapping.hpp
> +               ? 1
probably would get unreachable code warnings ...

2021-12-16 16:45 UTC, dalg24 approved these changes

2021-12-16 18:01 UTC, merged