Return input argument if no GPUs werde detected in get_gpu
kokkos/kokkos pull request #4623
Opened 2021-12-16 22:23 UTC by masterleinad

Fixes https://github.com/kokkos/kokkos/issues/4621. @jczhang07 Can you please take a look if this works for you?

Essentially, the changes here are only relevant for the SYCL backend. If a specific device is requested (id>=0) we still error out if there are no GPUs. If that is not the case (id<0), we use the default selector to run on a host queue if no GPUs are detected. This (intended) behavior is not changed here but we have `use_gpu` return the input argument when no GPU is detected (instead of assigning GPU 0 which doesn't exist in that case).

2021-12-16 22:51 UTC, dalg24 requested changes
This makes that code even less readable

2021-12-16 22:57 UTC, masterleinad commented
> This makes that code even less readable

What is it specifically that you want me to change? Are you criticizing the intended behavior or do you merely want to change the implementation to be more readable? 

In the latter case, we could copy
```
return sycl::device::get_devices(sycl::info::device_type::gpu).size();
```
before calling `get_gpu` in the SYCL case (although this function is then called twice for the regular case of running on a GPU). Would that make you accept the changes?

2021-12-17 00:21 UTC, jczhang07 commented
@masterleinad The fix works for me. Thanks.

2021-12-17 03:04 UTC, masterleinad commented
@dalg24 I avoided modifying `get_gpu` now but moved the logic to the respective `SYCL` call site.

2021-12-17 14:19 UTC, dalg24 approved these changes

2021-12-19 16:20 UTC, masterleinad commented
Retest this please.

2021-12-20 02:29 UTC, jczhang07 commented
> Retest this please.
@masterleinad Reested and it worked. Thanks.

2021-12-20 16:22 UTC, Rombur requested changes

2021-12-20 16:32 UTC, Rombur approved these changes

2021-12-20 16:56 UTC, dalg24 commented on core/src/SYCL/Kokkos_SYCL.cpp
> +  // requested.
```suggestion
  // If there are no GPUs return whatever else we can run on if no specific GPU
  // is requested.
```

2021-12-20 18:46 UTC, dalg24 commented
Retest this please

2021-12-21 01:10 UTC, jczhang07 commented
> Retest this please

Works here.

2021-12-21 17:50 UTC, masterleinad commented
Retest this please.

2021-12-21 17:51 UTC, masterleinad commented
> Works here.

@jczhang07 The comments are not for you but for our CI. :slightly_smiling_face:

2021-12-21 21:32 UTC, merged