Avoid using execution_space as View template argument
kokkos/kokkos pull request #4675
Opened 2022-01-14 16:32 UTC by masterleinad

Should also fix #3475.

2022-01-14 21:12 UTC, masterleinad commented
Retest this please.

2022-01-19 01:09 UTC, crtrott approved these changes

2022-01-19 14:54 UTC, masterleinad commented
> Is this still a work in progress or is it ready for review?

Seems like it worked immediately. :slightly_smiling_face:

2022-01-19 15:20 UTC, dalg24 commented
Also this is not adding any test.  Did you verify it resolves the issue reported?

2022-01-19 17:50 UTC, masterleinad commented
> Also this is not adding any test. How did you verify it resolves the issue reported?

I checked manually compiling with `UVM` and then setting the memory_space for `UnorderedMap` to `CudaSpace` in the `UnorderedMap` unit tests that we don't allocate in `UVM` space. I didn't check anything with respect to the other changes.

I'm not quite sure if we require a test here.

2022-01-24 20:13 UTC, crtrott requested changes
After thinking it more over I agree that DeviceType is better as the type than DeviceType::memory_space, it actually is closer to the original intend of using the optimal execution memory space for the chosen execution space.

2022-01-24 20:24 UTC, dalg24 commented on algorithms/src/Kokkos_Random.hpp
> +  using locks_type      = View<int**, typename DeviceType::memory_space>;
```suggestion
  using locks_type      = View<int**, DeviceType>;
```

2022-01-24 20:59 UTC, dalg24 commented on core/src/impl/Kokkos_ViewArray.hpp
> +        ViewValueFunctor<Kokkos::Device<execution_space, memory_space>,
PIng

2022-01-24 22:04 UTC, masterleinad commented on core/src/impl/Kokkos_ViewArray.hpp
> +        ViewValueFunctor<Kokkos::Device<execution_space, memory_space>,
See 820c00cf9.

2022-01-25 16:18 UTC, crtrott approved these changes
After thinking it more over I agree that DeviceType is better as the type than DeviceType::memory_space, it actually is closer to the original intend of using the optimal execution memory space for the chosen execution space.

2022-01-25 16:21 UTC, merged