Add int testing to bytes_and_flops
kokkos/kokkos pull request #4678
Opened 2022-01-14 22:21 UTC by crtrott

Also split the compilation into 4 source files

2022-01-14 22:39 UTC, crtrott commented
CUDA compile time on my machine went from 47s to 26s, even though I added int instantiation.

2022-01-14 22:40 UTC, dalg24 requested changes
Do not define new functions, just explicitly instantiate them

2022-01-14 22:40 UTC, dalg24 commented on benchmarks/bytes_and_flops/bench_double.cpp
> +}
```suggestion
template void run_stride_unroll<double>(int N, int K, int R, int D, int U, int F, int T, int S);
```
(not formatted and not double checked the signature)

2022-01-18 12:40 UTC, dalg24 commented on benchmarks/bytes_and_flops/main.cpp
> +void run_stride_unroll(int, int, int, int, int, int, int, int);
No.  Keep the header include and do `extern template ...` to skip the instantiation from that compile unit.
(I pushed a fix directly to your branch)

2022-01-18 12:40 UTC, dalg24 approved these changes

2022-01-18 14:51 UTC, crtrott commented
Retest this please.

2022-01-18 14:52 UTC, merged