[WIP] Avoid macros for CUDA lock arrays
kokkos/kokkos pull request #4682
Opened 2022-01-16 20:37 UTC by masterleinad

Trying the suggestion is #2235.

2022-01-18 21:00 UTC, masterleinad commented
Retest this please.

2022-02-14 20:41 UTC, masterleinad commented
We should of course critically examine if this works.

2022-02-15 16:20 UTC, dalg24 requested changes
Submit PR on Desul side

2022-06-02 17:58 UTC, dalg24 commented
Ping

2022-06-02 19:10 UTC, masterleinad commented
> Submit PR on Desul side

See https://github.com/desul/desul/pull/64.

2022-06-02 19:17 UTC, dalg24 commented
Please fix conflicts

2022-06-08 17:48 UTC, masterleinad commented
I update with the changes in `desul`.

2022-06-08 19:48 UTC, dalg24 reviewed
Do you know why we have both the Kokkos and the Desul lock arrays?

2022-06-08 20:16 UTC, masterleinad commented
> Do you know why we have both the Kokkos and the Desul lock arrays?

`g_device_cuda_lock_arrays` is also used in `Kokkos_Cuda_Parallel_Team.hpp`. 
I guess we could discuss changing that.

2022-06-08 20:26 UTC, masterleinad commented on core/src/Cuda/Kokkos_Cuda_Locks.hpp
> +                           sizeof(Kokkos::Impl::CudaLockArrays)));
See [f7d1303](https://github.com/kokkos/kokkos/pull/4682/commits/f7d1303e2ff25db9b085b1466f5a3f9b3869a37a).

2022-06-20 19:22 UTC, dalg24 approved these changes, later dismissed

2022-06-20 19:22 UTC, dalg24 commented on core/src/Cuda/Kokkos_Cuda_Locks.hpp
> +void inline ensure_cuda_lock_arrays_on_device() {}
```suggestion
inline void ensure_cuda_lock_arrays_on_device() {}
```

2022-06-20 19:22 UTC, dalg24 commented on core/src/Cuda/Kokkos_Cuda_Locks.hpp
> +void static inline ensure_cuda_lock_arrays_on_device() {
```suggestion
inline static void ensure_cuda_lock_arrays_on_device() {
```

2022-06-20 19:22 UTC, dalg24 commented on core/src/Cuda/Kokkos_Cuda_Locks.hpp
> +void static inline ensure_cuda_lock_arrays_on_device() {
```suggestion
inline static void ensure_cuda_lock_arrays_on_device() {
```

2022-06-20 19:27 UTC, crtrott approved these changes

2022-06-20 19:29 UTC, dalg24 commented
Does not pass CI

2022-06-20 19:52 UTC, masterleinad commented on core/src/Cuda/Kokkos_Cuda_Locks.hpp
> +void inline ensure_cuda_lock_arrays_on_device() {}
0a3e71b84c07d0677ad8f6d9d62e7f1017f757af

2022-06-20 19:52 UTC, masterleinad commented on core/src/Cuda/Kokkos_Cuda_Locks.hpp
> +void static inline ensure_cuda_lock_arrays_on_device() {
0a3e71b84c07d0677ad8f6d9d62e7f1017f757af

2022-06-21 17:58 UTC, dalg24 approved these changes

2022-06-21 17:58 UTC, merged