Update nvcc_wrapper
kokkos/kokkos pull request #4699
Opened 2022-01-19 20:29 UTC by Mark-E-Hamilton

Add mkdir to ensure that the temp directory exists before compiles.

2022-01-19 20:35 UTC, dalg24 commented
OK to test

2022-01-20 14:33 UTC, dalg24 commented
Failure is unrelated

2022-01-20 14:33 UTC, dalg24 commented
> Add mkdir to ensure that the temp directory exists before compiles.

Why do you think we should create it rather than error out if it doesn't already exist?

2022-01-20 20:55 UTC, Mark-E-Hamilton commented
We have automatic CI and nightly build process that fail when the compiler tries to write to a temporary directory that doesn't exist. Although we pre-create it, it is getting deleted by system processes that are cleaning out /tmp daily, which causes our builds to fail.  Putting this mkdir closer to the actual compile should make this less likely to fail. It seems like this should be done in the compiler, but we don't have access to that. It also seems that processes that need temporary directories should be the ones to create them, and not depend on a calling process to do it for them.

2022-04-26 09:44 UTC, MikolajZuzek approved these changes
Looks good!

2022-04-26 09:46 UTC, cz4rs approved these changes
Looks innocent enough. Is this still relevant? @Mark-E-Hamilton @dalg24

2022-04-26 12:11 UTC, dalg24 commented
I am still not convinced `nvcc_wrapper` should create the temporary directory if it does not exist.

2022-06-08 16:07 UTC, dalg24 requested changes
What prevents you to run the `mkdir -p ...` command in your CI script

2022-06-08 16:08 UTC, masterleinad requested changes
Agreeing with @dalg24. We should not extend what the compiler provides.

2022-06-08 16:08 UTC, dalg24 commented
Feel free to re-open if there is new information

2022-06-08 16:08 UTC, closed without merging