Add base-2/10 switch and iteration arg to bytes_and_flops
kokkos/kokkos pull request #4752
Opened 2022-02-03 17:11 UTC by arghdos

Change-Id: I767002da3003b0b15e07abefcbd9faf6629e5043

2022-02-03 17:35 UTC, dalg24 requested changes

2022-02-03 17:35 UTC, dalg24 commented on benchmarks/bytes_and_flops/main.cpp
> +    return 0;
I love that we return success error code.  (not asking you to change I see it is consistent with what was there before)

2022-02-03 17:35 UTC, dalg24 commented on benchmarks/bytes_and_flops/main.cpp
> +  }
```suggestion
  if (I < 1) {
    printf("I must be >= 1\n");
    return 0;
  }
```

2022-02-03 17:35 UTC, dalg24 commented on benchmarks/bytes_and_flops/main.cpp
> +    printf("  I:   iterations of the kernel to time over(default=10)");
```suggestion
    printf("  I:   iterations of the kernel to time over (default=10)\n");
```

2022-02-03 17:35 UTC, dalg24 commented on benchmarks/bytes_and_flops/main.cpp
> +        "default=2)");
```suggestion
        "default=2)\n");
```

2022-02-03 17:35 UTC, dalg24 commented on benchmarks/bytes_and_flops/main.cpp
> +    printf("Arguments: N K R D U F T S B\n");
```suggestion
    printf("Arguments: N K R D U F T S B I\n");
```

2022-02-18 18:56 UTC, Rombur approved these changes

2022-03-02 20:17 UTC, crtrott approved these changes

2022-03-02 20:17 UTC, merged