Deprecate OffsetView constructors taking index_list_type
kokkos/kokkos pull request #4810
Opened 2022-02-21 20:13 UTC by masterleinad

While looking at https://github.com/kokkos/kokkos/pull/4805, I found a `OffsetView` constructor taking `index_list_type`,i.e., `std::initializer_list`, objects as argument to denote begin and end for every dimension. This pull request deprecates that behavior to use `std::pair` instead so that specifying too many arguments is not possible.

2022-02-22 14:51 UTC, dalg24 reviewed
Looks fine beside the adding `Kokkos::Experimental::range_type`

2022-02-22 14:51 UTC, dalg24 commented on containers/src/Kokkos_OffsetView.hpp
> +using range_type      = std::pair<int64_t, int64_t>;
I am not sure about adding that guy.  I am surprised we defined `index_list_type` like that in the first place.

2022-02-22 15:37 UTC, masterleinad commented
> Looks fine beside the adding Kokkos::Experimental::range_type

Do you prefer to use `std::pair` directly instead of the alias then?

2022-02-22 15:43 UTC, dalg24 commented
As long we are not injecting an alias in the namespace.
Note that you could write your constructor to take anything that supports `std::get<{0,1}>(R const&)` with `std::tuple_size<R>::value==2`

2022-02-22 16:57 UTC, masterleinad commented
> Note that you could write your constructor to take anything that supports `std::get<{0,1}>(R const&)` with `std::tuple_size<R>::value==2`

I prefer to have a constructor that allows me to do 
```
offset_view_type("o1", {-1, 3}, {-2,2});
```
and I don't see a need to introduce another templated one taking other tuple-like containers yet.

2022-02-22 22:36 UTC, dalg24 requested changes
Comment about the design choices above the constructor.

2022-02-22 23:26 UTC, dalg24 approved these changes

2022-02-23 04:55 UTC, masterleinad commented
Retest this please.

2022-02-23 14:03 UTC, Rombur approved these changes

2022-03-02 20:20 UTC, crtrott approved these changes

2022-03-02 20:20 UTC, merged