OpenMPTarget: Enable tiling for MDRange policies.
kokkos/kokkos pull request #5104
Opened 2022-06-09 19:26 UTC by rgayatri23

2022-06-09 19:52 UTC, dalg24 commented
Did you try on AMD?

2022-06-10 03:42 UTC, rgayatri23 commented
> Did you try on AMD?

No not yet. AMD is still giving linktime issues that I need to debug.

2022-06-10 18:33 UTC, dalg24 requested changes
You must provide a description
Make sure you include a rational for these changes

2022-06-14 20:33 UTC, dalg24 commented
> > Did you try on AMD?
> 
> No not yet. AMD is still giving linktime issues that I need to debug.

Please do so.
You may comment out as many non MDRangePolicy tests as you like but please check that it works.

2023-03-24 22:03 UTC, closed without merging