Threads: Fix serial resizing scratch space
kokkos/kokkos pull request #5109
Opened 2022-06-10 16:01 UTC by masterleinad

Fixes #5107. This pull request reverts parts of #4499 and makes sure that we call 
```
s_threads_process.m_pool_state = ThreadsExec::Active;
```
after deallocating scratch space (if necessary) to avoid deadlocking.

2022-06-14 12:42 UTC, dalg24 commented
I assume you meant [#487{6 -> 8}](https://github.com/kokkos/kokkos/pull/4878)

2022-06-14 12:51 UTC, masterleinad commented
> I assume you meant [#487{6 -> 8}](https://github.com/kokkos/kokkos/pull/4878)

Yes, thanks.

2022-06-14 12:56 UTC, masterleinad commented on core/src/Threads/Kokkos_ThreadsExec.cpp
>    using Record = Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>;
See 5ab11f6a0.

2022-06-16 14:45 UTC, crtrott requested changes
Just one more thing: you renamed one function to many. The resize_thread_scratch_serial name for the outer function was actually good. See my comments

2022-06-16 14:45 UTC, crtrott commented on core/src/Threads/Kokkos_ThreadsExec.cpp
> +void ThreadsExec::first_touch_allocate_thread_private_scratch_in_serial() {
I think this one actually should be `resize_scratch_serial` (since it does the entire resize dealloc + alloc)

2022-06-16 14:45 UTC, crtrott commented on core/src/Threads/Kokkos_ThreadsExec.cpp
> +void ThreadsExec::first_touch_allocate_thread_private_scratch(ThreadsExec &exec,
jup this name is good.

2022-06-16 15:42 UTC, crtrott approved these changes

2022-06-16 19:07 UTC, dalg24 approved these changes

2022-06-16 19:08 UTC, merged