Remove NUMA related arguments in Threads backend initialization
kokkos/kokkos pull request #5121
Opened 2022-06-16 20:10 UTC by dalg24

Following up on #5117 
This PR does not do much besides pushing all legacy initialization code into `Impl::ThreadsExec::initialize` and make the code more consistent with the OpenMP backend interface
https://github.com/kokkos/kokkos/blob/98b6ba9cf59f79c05af5d2ebd2e637d482a54f1b/core/src/Kokkos_OpenMP.hpp#L150
https://github.com/kokkos/kokkos/blob/98b6ba9cf59f79c05af5d2ebd2e637d482a54f1b/core/src/OpenMP/Kokkos_OpenMP_Instance.hpp#L103

Drive-by cleanup of `Impl::{Threads,OpenMP}SpaceInitializer::initialize`

2022-06-16 20:15 UTC, dalg24 commented on core/src/Threads/Kokkos_ThreadsExec.cpp
> -                   Kokkos::HostSpace::execution_space>::value) {
I fail to see how that would not be always true and definitely would not want to silently do nothing anyway

2022-06-17 00:43 UTC, ldh4 approved these changes

2022-06-17 21:22 UTC, crtrott approved these changes

2022-06-17 21:24 UTC, crtrott requested changes
what about that async threadpool thing?

2022-06-17 21:52 UTC, closed without merging

2022-06-17 21:53 UTC, dalg24 commented
Did not mean to close

> what about that async threadpool thing?

what do you mean?