Provide ViewCtorProp overload for create_mirror_view_and_copy
kokkos/kokkos pull request #5125
Opened 2022-06-17 21:45 UTC by masterleinad

Similar to #5095, #5035 and #4844. #4826 would help remove more fences here.

This pull request provides a `ViewCtorProp` overload for `create_mirror_view_and_copy` that also allows specifying an execution space to be used in the `allocation` and the `deep_copy`. The existing version is changed to always use an execution space for `allocation` (but still uses the two-argument `deep_copy`).

2022-06-22 18:12 UTC, PhilMiller commented
This advances #4792.

Per the description, this'll need some follow-up in the spirit of #4793. Not a reason not to move this forward now.

2022-07-07 18:10 UTC, crtrott requested changes
Just not sure about that cast

2022-07-07 18:10 UTC, crtrott commented on containers/src/Kokkos_DynamicView.hpp
> +        static_cast<Impl::ViewCtorProp<void, ExecutionSpace>&>(arg_prop_copy)
is this safe?

2022-07-07 18:14 UTC, crtrott approved these changes
Ok its fine, cast is making use of inheritance.

2022-07-08 16:57 UTC, JBludau approved these changes
Looks reasonable, although the change to `TEST_EXECSPACE` in [6ce5a9](https://github.com/kokkos/kokkos/pull/5125/commits/6ce5a947d9dd1aa2fa762ae16620df405c231a4a) could be done in a separate pr (including other tests in containers that might benefit)

2022-07-08 17:15 UTC, merged