Deprecate parallel_* overloads taking the label as later argument
kokkos/kokkos pull request #5141
Opened 2022-06-23 22:04 UTC by masterleinad

This is not even documented, see https://github.com/kokkos/kokkos/wiki/Kokkos::parallel_for, https://github.com/kokkos/kokkos/wiki/Kokkos::parallel_reduce, and https://github.com/kokkos/kokkos/wiki/Kokkos::parallel_scan.

2022-06-23 23:27 UTC, dalg24 approved these changes
I'd prefer if you didn't qualify the traits

2022-06-23 23:27 UTC, dalg24 commented on core/src/Kokkos_Parallel.hpp
> +              std::enable_if_t<Kokkos::is_execution_policy<ExecPolicy>::value>>
```suggestion
              std::enable_if_t<is_execution_policy<ExecPolicy>::value>>
```

2022-06-23 23:27 UTC, dalg24 commented on core/src/Kokkos_Parallel.hpp
> +              std::enable_if_t<Kokkos::is_execution_policy<ExecPolicy>::value>>
Same comment for all occurrences below

2022-06-24 01:55 UTC, dalg24 commented on core/src/Kokkos_Parallel.hpp
> +  ::Kokkos::parallel_scan("", work_count, functor);
```suggestion
  ::Kokkos::parallel_scan(str, work_count, functor);
```

2022-06-29 15:46 UTC, crtrott requested changes

2022-06-29 15:46 UTC, crtrott commented on core/src/Kokkos_Parallel.hpp
> +inline void parallel_scan(
Annotate with the deprecation attribute?

2022-06-29 17:29 UTC, cz4rs approved these changes
Looks good to me.

2022-06-29 22:22 UTC, merged