Move min, max, clamp, minmax routines out of Experimental namespace
kokkos/kokkos pull request #5170
Opened 2022-06-30 18:44 UTC by ajpowelsnl

I propose moving the min, max, clamp and minmax routines out of the `Experimental` namespace, and into the `Kokkos` namespace.

I developed these changes using this build: 

```
cmake \
-DKokkos_ENABLE_TESTS=ON \
-DKokkos_ENABLE_CUDA=ON \
-DKokkos_ENABLE_CUDA_LAMBDA=ON \
-DKokkos_ARCH_VOLTA70=ON \
-DKokkos_ENABLE_SERIAL=ON \
-DCMAKE_CXX_STANDARD=14 \
-DCMAKE_BUILD_TYPE=Release ..\

```

I ran all unit tests thusly:

`ctest --output-on-failure`

All tests passed.

2022-06-30 18:53 UTC, masterleinad requested changes
We should rather deprecate using the functions in the `Experimental` namespace rather than outright removing them.
Also, you need to fix the indentation using `clang-format-8`.

2022-07-01 09:05 UTC, fnrizzi commented
I agree on deprecating

2022-07-07 20:19 UTC, masterleinad reviewed
The only disadvantage with this approach I see is that we don't get deprecation warnings. Of course, we followed the same approach when promoting the math functions from the `Experimental` namespace.

2022-07-08 07:10 UTC, fnrizzi approved these changes

2022-07-08 07:10 UTC, fnrizzi commented
if this is how the math functins were promoted, i am ok with this

2022-07-08 15:11 UTC, merged