SYCL: Store device_id passed from initialization
kokkos/kokkos pull request #5246
Opened 2022-07-20 16:02 UTC by masterleinad

To the best of my knowledge, there is no other way to obtain unique information about the `sycl::device` used, thus just storing what was given as `device_id` during initialization seems the best we can do. It's debatable what to do if the user passes just a `sycl::queue` add the moment we just use 0 by default but we could also use the `device_id` the singleton was initialized with.

2022-07-27 20:24 UTC, dalg24 requested changes

2022-07-27 20:24 UTC, dalg24 commented on core/src/Kokkos_SYCL.hpp
> +  static int sycl_device();
Absolutely cannot be called `sycl_device` as it is misleading users.
One could expect it returns `sycl::device` just like `sycl_queue() -> sycl::queue`.
I don't think we need to expose any public member in the execution space class for it.
```suggestion
```
Instead do
```C++
template <>
struct DeviceTypeTraits<Kokkos::Experimental::SYCL> {
  static constexpr DeviceType id = DeviceType::SYCL;
  static int device_id(const Kokkos::Experimental::SYCL& exec) {
    return exec.impl_internal_space_instance().m_syclDev;
  }
};
```

2022-07-27 20:24 UTC, dalg24 commented on core/src/SYCL/Kokkos_SYCL.cpp
> +  Impl::SYCLInternal::singleton().initialize(gpu_devices[id], id);
No need to propagate this to `SYCLInternal::initialize`.  Do
```suggestion
  Impl::SYCLInternal::singleton().initialize(gpu_devices[id]);
  Impl::SYCLInternal::m_syclDev = id;
```

2022-07-27 21:51 UTC, masterleinad commented
@dalg24 I followed your suggestions.

2022-07-27 21:59 UTC, dalg24 approved these changes

2022-07-28 14:49 UTC, masterleinad commented
For some reason, `OpenACC` can't find a device in one test
```
Test command: /var/jenkins/workspace/Kokkos/build/core/unit_test/KokkosCore_IncrementalTest_OPENACC
33: Test timeout computed to be: 1500
33: Error: no GPU available for execution.
33:  Raised by Kokkos::initialize().
33: 
33: Backtrace:
33:                         [0x4b2453]
33:                         [0x490463]
33:                         [0x485cf3]
33:                         [0x485e32]
33:                         [0x4b68d1]
33:                         [0x48e81c]
33:                         [0x48a048]
33:                         [0x412fdd]
33: __libc_start_main [0x7f29a846e0b3]
33:                         [0x412e6e]
33/48 Test #33: KokkosCore_IncrementalTest_OPENACC ...........Subprocess aborted***Exception:   0.19 sec
```
That's clearly unrelated to this pull request that only touches `SYCL` fails and I have seen this failure in other pull requests, too.

2022-07-29 16:46 UTC, JBludau approved these changes
looks good

2022-07-29 21:53 UTC, dalg24 commented
Failure was unrelated (OpenACC issue about GPU architecture being wrong that is been resolved on `develop`)

2022-07-29 21:53 UTC, merged