Don't set a flag for MSVC using ARCH_NATIVE
kokkos/kokkos pull request #5316
Opened 2022-08-08 18:28 UTC by masterleinad

2022-08-08 19:28 UTC, dalg24 commented on cmake/kokkos_arch.cmake
> +    MSVC    NO-VALUE-SPECIFIED
Why is that the right thing to do rather than error out and say the option is not available?
The proposed resolution is likely so surprise users.

2022-08-08 19:35 UTC, crtrott requested changes
Just looked up the default behavior of MSVC: it is not native, it is SSE2: 

https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-170

Hence we should not do this, and rather error out or. Users can specify Kokkos_ARCH_NONE to get nothing set.

2022-08-08 20:02 UTC, masterleinad commented
> Hence we should not do this, and rather error out or. 

Changed.

2022-08-08 20:04 UTC, masterleinad commented on cmake/kokkos_arch.cmake
> +IF (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR "x${CMAKE_CXX_SIMULATE_ID}" STREQUAL "xMSVC")
`MSVC` is a variable in `CMake`, see https://cmake.org/cmake/help/latest/variable/MSVC.html. Thus, we have to use quotes here.

2022-08-09 13:51 UTC, dalg24 approved these changes

2022-08-09 20:59 UTC, crtrott approved these changes

2022-08-09 21:00 UTC, dalg24 commented
Failure (CUDA UM perf test) is unrelated

2022-08-09 21:00 UTC, merged