Test device ID and number of threads after initialization
kokkos/kokkos pull request #5328
Opened 2022-08-12 12:12 UTC by dalg24

Intended as a replacement for 
https://github.com/kokkos/kokkos/blob/839df99bcfc94fce4055aa629048b3a7f5b61eee/core/unit_test/CMakeLists.txt#L881-L888

2022-08-12 17:03 UTC, dalg24 commented on core/unit_test/CMakeLists.txt
> +    USE_SOURCE_PERMISSIONS
This was added in CMake 3.20

2022-08-15 13:25 UTC, Rombur requested changes

2022-08-15 16:15 UTC, JBludau commented on core/unit_test/UnitTest_DeviceAndThreads.cpp
> +#include <Kokkos_Core.hpp>
done in [6d4b49](https://github.com/kokkos/kokkos/pull/5328/commits/6d4b49b1bd7421fa12f7d65c36c994c8140772c5)

2022-08-15 16:16 UTC, JBludau commented on core/unit_test/TestDeviceAndThreads.py
> +import unittest
done in [21807a](https://github.com/kokkos/kokkos/pull/5328/commits/21807ab584a394a3790aae19b9034e44cc443218)

2022-08-17 17:50 UTC, crtrott requested changes

2022-08-17 17:50 UTC, crtrott commented on core/unit_test/TestDeviceAndThreads.py
> +        for num_threads in range(1, max_threads + 1):
Let not do every single one. just choose like 3 or so, say 1, 3 and max_threads (3 so we have a non-power of two)

2022-08-17 17:52 UTC, Rombur approved these changes

2022-08-17 22:25 UTC, JBludau approved these changes

2022-08-19 13:26 UTC, dalg24 commented
Didn't mean to re-request Bruno's review...
Christian please go ahead and suggest changes on the PR if you really want to reduce further the number of tests that set num_threads

2022-08-24 14:25 UTC, merged