Guard t_openmp_instance with KOKKOS_ENABLE_DEPRECATED_CODE_3
kokkos/kokkos pull request #5396
Opened 2022-08-26 16:42 UTC by masterleinad

Following https://github.com/kokkos/kokkos/pull/5105#discussion_r948338397, this pull request guards `t_openmp_instance` with `KOKKOS_ENABLE_DEPRECATED_CODE_3` such that it's removed when removing `partition_master`.

2022-08-26 17:31 UTC, PhilMiller commented
I know I'm again jumping the gun on a draft PR, but is this also going to need to be applied to 3.7, since it's an added 3.x deprecation?

2022-08-26 18:22 UTC, masterleinad commented
> I know I'm again jumping the gun on a draft PR, but is this also going to need to be applied to 3.7, since it's an added 3.x deprecation?

The changes here are purely internal and it's merely intended for us not to forget removing the variable as well as making sure that everything apart from `partition_master` really works without it.

2022-08-26 18:24 UTC, masterleinad commented
Retest this please.

2022-08-29 17:33 UTC, masterleinad commented
Only the `OPENMPTARGET-Clang` CI is timing out. This looks unrelated.

2022-08-29 18:46 UTC, Rombur requested changes
I would prefer that we do not merge this PR for the moment. This will create unnecessary conflicts with #5105 The `FIXME_OPENMP` are enough for now.

2022-08-31 20:10 UTC, crtrott commented
I leave this up to Bruno if he wants this or not. I don't think its necessary there are already FIXME comments, and its not public code anyway.

2022-09-18 00:39 UTC, crtrott commented
@Rombur what do you want to do with this?

2022-12-13 16:29 UTC, masterleinad commented
Retest this please.

2022-12-13 16:41 UTC, dalg24 commented on core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp
> +#ifdef KOKKOS_ENALBE_DEPRECATED_CODE_3
```suggestion
#ifdef KOKKOS_ENALBE_DEPRECATED_CODE_3
```

2022-12-13 17:04 UTC, Rombur approved these changes

2022-12-20 12:49 UTC, dalg24 approved these changes

2022-12-20 12:49 UTC, merged