HIP: Initialize device-related variables only by the singleton
kokkos/kokkos pull request #5444
Opened 2022-09-08 13:55 UTC by masterleinad

Analogous to #5442 for HIP.

2022-09-08 16:48 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP.cpp
> +  const auto& dev_info = Impl::HIPInternalDevices::singleton();
If we are refactoring we should just get rid of that `Impl::HIPInternalDevices` altogether

2022-09-09 22:10 UTC, dalg24 requested changes
Note that it likely conflicts with #5448

2022-09-09 22:10 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP.cpp
> +  const int hip_device_id = ::Kokkos::Impl::get_gpu(settings);
```suggestion
  const int hip_device_id = Impl::get_gpu(settings);
```

2022-09-09 22:10 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP.cpp
> +  if (ok_id) {
This is unnecessary.  The `device_id` validation is done by Kokkos Core

2022-09-09 22:10 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP.cpp
> +  ::Kokkos::Impl::initialize_host_hip_lock_arrays();
```suggestion
  Impl::initialize_host_hip_lock_arrays();
```

2022-09-09 22:10 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_Instance.cpp
> +int Impl::HIPInternal::m_hipArch                                          = -1;
Declare them `inline` and define them inside the `HIPInternal` class definition instead?

2022-09-09 22:10 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_Instance.hpp
> +  static hipDeviceProp_t m_deviceProp;
Readability, move it next to the other static members

2022-09-12 23:26 UTC, ldh4 commented on core/src/HIP/Kokkos_HIP.cpp
> +  KOKKOS_IMPL_HIP_SAFE_CALL(hipGetDeviceCount(&hipDevCount));
Seeing that `HIP::detect_device_count()` now does the same thing as this line,

```suggestion
  int hipDevCount = HIP::detect_device_count();
```

2022-09-15 13:06 UTC, masterleinad commented
THE HIP CI builds pass. A couple of CUDA CI steps fail because the tester was running out of disk space.

2022-09-15 13:07 UTC, masterleinad commented
Updated after #5448 was merged.

2022-09-15 15:44 UTC, dalg24 approved these changes
Fine by me but requiring approval of Bruno

2022-09-19 12:18 UTC, Rombur approved these changes
Looks fine but you need to fix the conflict.

2022-09-19 12:20 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_Instance.cpp
> +int Impl::HIPInternal::m_hipArch                                          = -1;
Ping

2022-09-19 13:15 UTC, masterleinad commented
> Looks fine but you need to fix the conflict.

Merged with `develop` again...

2022-09-21 12:31 UTC, Rombur commented
This can be merged. The CI failures are clearly unrelated.

2022-09-21 13:40 UTC, merged