Allow as_view_of_rank_n() to be overloaded for "special" scalar types
kokkos/kokkos pull request #5491
Opened 2022-09-23 19:33 UTC by etphipp

as_view_of_rank_n() needs to be overloaded for special scalar types like Sacado that need to pass a hidden dimension.  This change adds the necessary SFINAE stuff to allow that to happen.  This will require adding the new overload in Trilinos/Sacado.

For Trilinos issue [#11018](https://github.com/trilinos/Trilinos/issues/11018) causing runtime failures in Albany.

@PhilMiller, @ndellingwood

2022-09-23 20:25 UTC, masterleinad commented
You probably also want to change the original template https://github.com/kokkos/kokkos/blob/b152efa94bc38d597870e5a275194cc00ed5afbf/core/src/Kokkos_View.hpp#L1732-L1749, right?

2022-09-23 20:26 UTC, masterleinad commented
Also, the indentation is off: https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/10673/pipeline
You'll need to use `clang-format-8` (or apply the patch in the link).

2022-09-23 20:33 UTC, etphipp commented
> You probably also want to change the original template
> 
> https://github.com/kokkos/kokkos/blob/b152efa94bc38d597870e5a275194cc00ed5afbf/core/src/Kokkos_View.hpp#L1732-L1749
> , right?

No, I don't think so.  Those overloads are fine.

2022-09-23 20:37 UTC, masterleinad commented
> No, I don't think so. Those overloads are fine.

You are saying/promising that you will never want to specialize them?

2022-09-23 20:41 UTC, etphipp commented
> > No, I don't think so. Those overloads are fine.
> 
> You are saying/promising that you will never want to specialize them?

I can't see any reason why they would need to be specialized.

2022-09-23 21:06 UTC, PhilMiller commented
> > > No, I don't think so. Those overloads are fine.
> > 
> > 
> > You are saying/promising that you will never want to specialize them?
> 
> I can't see any reason why they would need to be specialized.

That doesn't really make sense to me. If Sacado needs special treatment of a DynRankView, what lets it do without the same special treatment of a common View? Is it purely coincidence of the current implementations in Kokkos, or something structural?

2022-09-23 21:09 UTC, etphipp commented
> That doesn't really make sense to me. If Sacado needs special treatment of a DynRankView, what lets it do without the same special treatment of a common View? Is it purely coincidence of the current implementations in Kokkos, or something structural?

These functions don't create a new view.  If either did, it likely would need specialization.

2022-09-23 21:15 UTC, masterleinad commented
This pull request makes `as_view_of_rank_n` a customization point for `DynRankView` but not for any other type. I think it's safer to do it consistently so that if we ever decide to have another specialization, we also take into consideration that someone else (I think `Sacado` is the only one doing these kinds of things at te moment) might want to use it as a customization point.

2022-09-23 21:19 UTC, PhilMiller commented
That's my preference too. If any overload of a function needs to be guarded for specialization, please apply the guard to all of them. Otherwise, we end up with way more opportunities for changes on our side to produce unexpected errors on yours

2022-09-26 12:33 UTC, masterleinad requested changes
Make the same restrictions on the original template.

2022-09-28 18:11 UTC, ndellingwood commented
Added patch release label for 3.7.01 patch release

2022-09-28 19:49 UTC, masterleinad approved these changes

2022-09-29 12:41 UTC, masterleinad commented
```
/__w/kokkos/kokkos/containers/unit_tests/../src/Kokkos_DynRankView.hpp:1694:77: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
```

2022-09-29 20:45 UTC, PhilMiller approved these changes
In a few years, all this SFINAE specialization cruft can go away with C++20 `requires`. Of course, by then, we expect that we'll have used MDSpan support to drastically simplify how Sacado builds FAD support onto Kokkos Views.

C'est la vie

2022-09-29 22:47 UTC, ndellingwood commented
CUDA-11.0-NVCC-C++17-RDC failure is CI issue, unrelated to PR:
```
+ docker build -t 558bd9e52e241f408d7b44ab2e4548b114eac94a --build-arg BASE=nvidia/cuda:11.0-devel --build-arg ADDITIONAL_PACKAGES=g++-8 gfortran clang --build-arg CMAKE_VERSION=3.17.3 -f scripts/docker/Dockerfile.nvcc scripts/docker

Sending build context to Docker daemon  23.04kB

Step 1/10 : ARG BASE=nvidia/cuda:9.2-devel

Step 2/10 : FROM $BASE

manifest for nvidia/cuda:11.0-devel not found: manifest unknown: manifest unknown

script returned exit code 1
```

2022-10-03 14:39 UTC, Rombur commented
Retest this please

2022-10-05 02:51 UTC, ndellingwood commented
fedora:rawhide, clang++, Release/Debug, OPENMP failure is a CI issue?
```
 -- Build files have been written to: /__w/kokkos/kokkos/example/build_cmake_installed/builddir
Scanning dependencies of target example
[ 33%] Building CXX object CMakeFiles/example.dir/cmake_example.cpp.o
[ 66%] Building Fortran object CMakeFiles/example.dir/foo.f.o
[100%] Linking CXX executable example
/usr/bin/ld: CMakeFiles/example.dir/foo.f.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/example.dir/build.make:119: example] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/example.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2
Error: Process completed with exit code 2.
```

2022-10-05 12:29 UTC, masterleinad commented
> fedora:rawhide, clang++, Release/Debug, OPENMP failure is a CI issue?

Yes, see https://github.com/kokkos/ci-containers/pull/28.

2022-10-05 15:42 UTC, merged

2022-10-07 20:17 UTC, ndellingwood commented
@etphipp thanks for you work on this! With this update approved+merged I think work on the corresponding Sacado updates can move forward (and without corresponding Sacado updates we will have compilation failures when testing Trilinos against Kokkos' develop branch, e.g. from intrepid2):
```
/ascldap/users/ndellin/trilinos/Trilinos/kokkos/containers/src/Kokkos_DynRankView.hpp(1740): error: no instance of overloaded function "Kokkos::Impl::as_view_of_rank_n" matches the argument list
            argument types are: (const Kokkos::DynRankView<Sacado::Fad::SFad<double, 10>, Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>)
          detected during:
            instantiation of "Kokkos::ViewTraits<DataType *******, Properties...>::array_layout Kokkos::DynRankView<DataType, Properties...>::layout() const [with DataType=Sacado::Fad::SFad<double, 10>, Properties=<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>]"
/ascldap/users/ndellin/trilinos/Trilinos/packages/sacado/src/Kokkos_DynRankView_Fad.hpp(1198): here
            instantiation of "Kokkos::DynRankView<T, P...>::HostMirror Kokkos::create_mirror(const Kokkos::DynRankView<T, P...> &, std::enable_if<<expression>, void>::type *) [with T=Sacado::Fad::SFad<double, 10>, P=<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>>]"
```

If you put in a PR to Trilinos please include these Kokkos-related changes as well (they'll get clobbered by the identical changes during the next release). We are moving closer to cutting the next release candidate, but the release process can take some time to complete (especially for a major release)

2022-10-20 21:07 UTC, dalg24 commented on core/src/Kokkos_View.hpp
> +KOKKOS_FUNCTION std::enable_if_t<
This causes
```
warning: calling a __host__ function from a __host__ __device__ function is not allowed
```
reported by @ldh4