cmake: define KOKKOS_ARCH_A64FX
kokkos/kokkos pull request #5500
Opened 2022-09-28 20:11 UTC by e10harvey

2022-09-28 20:17 UTC, dalg24 approved these changes
Somehow we add only added with the makefiles...

2022-09-28 20:20 UTC, e10harvey commented
retest this please

2022-09-28 20:45 UTC, masterleinad requested changes

2022-09-28 20:45 UTC, masterleinad commented on core/src/impl/Kokkos_ViewMapping.hpp
>  #ifndef KOKKOS_ARCH_A64FX
Join the two `#ifdef`s.

2022-09-28 20:58 UTC, masterleinad approved these changes

2022-09-28 23:51 UTC, ndellingwood approved these changes

2022-09-29 13:01 UTC, dalg24 commented
Ignoring CUDA failures due to issues with one of the machines

2022-09-29 13:01 UTC, merged