SYCL:  Remove workaround for submit_barrier not being enqueued properly
kokkos/kokkos pull request #5504
Opened 2022-09-29 14:42 UTC by masterleinad

Needs https://github.com/intel/llvm/pull/6359 and https://github.com/intel/llvm/pull/6888 (or manually setting `SYCL_PI_LEVEL_ZERO_USE_MULTIPLE_COMMANDLIST_BARRIERS=1` as environment variable).
Also updates the AOT architectures.
I would consider merging it already if it passes CI (which I expect).

2023-03-16 18:27 UTC, dalg24 requested changes

2023-03-16 18:27 UTC, dalg24 commented on core/src/SYCL/Kokkos_SYCL_Space.cpp
>    auto event = q.memcpy(dst, src, n);
```suggestion
  auto event     = q.memcpy(dst, src, n);

```

2023-03-16 20:45 UTC, dalg24 approved these changes

2023-03-16 21:02 UTC, Rombur approved these changes

2023-03-16 21:16 UTC, dalg24 commented
Will ignore failure in the CUDA RDC build
```
5: [ RUN      ] cuda.workgraph_fib
5: /var/jenkins/workspace/Kokkos/core/unit_test/TestWorkGraph.hpp:127: Failure
5: Expected equality of these values:
5:   h_values(0)
5:     Which is: 322
5:   full_fibonacci(m_input)
5:     Which is: 377
5: [  FAILED  ] cuda.workgraph_fib (1366 ms)
```

2023-04-11 18:16 UTC, merged

2023-04-14 12:30 UTC, dalg24 commented
Uggg I merged with SYCL CI build failing...

2023-04-14 12:39 UTC, masterleinad commented
> Uggg I merged with SYCL CI build failing...

Yes, I also missed checking again...