Make SYCL::concurrency non-static
kokkos/kokkos pull request #5682
Opened 2022-12-13 17:17 UTC by masterleinad

Corresponding to #5669. It seems that we don't need `g_host_cuda_lock_arrays` (probably even after merging the generic atomics pull request). Hence, I haven't included a static `SYCLInternal::concurrency` function.

2022-12-13 20:51 UTC, crtrott requested changes

2022-12-13 20:51 UTC, crtrott commented on core/src/SYCL/Kokkos_SYCL.cpp
> +  return Impl::SYCLInternal::singleton().m_maxConcurrency;
why not return `m_space_instance->m_maxConcurrency`?

2022-12-14 20:34 UTC, crtrott approved these changes

2022-12-14 21:12 UTC, ldh4 approved these changes

2022-12-15 04:11 UTC, dalg24 commented
SYCL build passed.  Ignoring unrelated failures.

2022-12-15 04:11 UTC, merged