Upgrade NVHPC SDK version in CI
kokkos/kokkos pull request #5685
Opened 2022-12-14 15:56 UTC by dalg24

Attempt to resolve
```
nvc++-Error-A CUDA toolkit matching the current driver version (12.0) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK.
```
following CUDA drivers update on some of the CI machines

2022-12-14 16:11 UTC, masterleinad approved these changes

2022-12-14 16:14 UTC, fnrizzi approved these changes

2022-12-14 18:49 UTC, dalg24 commented on core/unit_test/TestJoinBackwardCompatibility.hpp
> +    !(defined(KOKKOS_ENABLE_CUDA) && defined(KOKKOS_COMPILER_NVHPC))
This is a "regression" from 22.9
cc @scottbiersdorff

2022-12-15 00:07 UTC, crtrott requested changes
I want to test a simpler resolution with staying at nvhpc 22.9 for now

2022-12-15 03:43 UTC, dalg24 commented
NVHPC build gives
```
4: [----------] 157 tests from cuda (183526 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 157 tests from 1 test suite ran. (183526 ms total)
4: [  PASSED  ] 152 tests.
4: [  SKIPPED ] 1 test, listed below:
4: [  SKIPPED ] cuda.host_shared_ptr_dereference_on_device
4: [  FAILED  ] 4 tests, listed below:
4: [  FAILED  ] cuda.local_deepcopy_teampolicy_layoutleft
4: [  FAILED  ] cuda.local_deepcopy_rangepolicy_layoutleft
4: [  FAILED  ] cuda.local_deepcopy_teampolicy_layoutright
4: [  FAILED  ] cuda.local_deepcopy_rangepolicy_layoutright
4: 
4:  4 FAILED TESTS
 4/41 Test  #4: KokkosCore_UnitTest_Cuda1 ....................***Failed  Error regular expression found in output. Regex=[  FAILED  ]183.99 sec

2022-12-15 12:48 UTC, dalg24 commented
Closing in favor of #5686

2022-12-15 12:48 UTC, closed without merging