[3.7.02] Set the correct device/context in InterOp tests
kokkos/kokkos pull request #5701
Opened 2022-12-16 20:52 UTC by masterleinad

Cherry-picking #5634.

2022-12-16 23:49 UTC, ndellingwood submitted a review, later dismissed

2022-12-20 12:51 UTC, dalg24 approved these changes

2023-02-01 18:05 UTC, dalg24 commented
Ignoring NVHPC toolchain issues

2023-02-01 19:10 UTC, dalg24 requested changes
PR is against master...
Please target the 3.7.2 RC branch

2023-02-02 02:36 UTC, dalg24 commented
Same NVHPC failures + one timing-based CUDA build.  Ignoring.

2023-02-02 02:36 UTC, merged