SYCL: Pass Xsycl-target-backend* only to the linker
kokkos/kokkos pull request #5705
Opened 2022-12-19 16:21 UTC by masterleinad

Without this, I get warnings such as
```
-Xsycl-target-backend -device 12.60.7’ [-Wunused-command-line-argument].
```
The option really only is used by the linker for AOT compilation.

2023-01-25 23:15 UTC, lucbv approved these changes
Yep, I want that too!

2023-01-28 13:01 UTC, dalg24 requested changes
OK with the changes to the cmake file, not OK with the line addition in the jenkinsfile

2023-01-30 14:29 UTC, masterleinad commented
> OK with the changes to the cmake file, not OK with the line addition in the jenkinsfile

Rebased on top of `develop`.

2023-01-30 22:56 UTC, dalg24 approved these changes

2023-01-30 22:56 UTC, merged