Spell out Kokkos::ALL_t to avoid deprecation warnings
kokkos/kokkos pull request #5818
Opened 2023-01-26 21:19 UTC by masterleinad

Deprecations don't get caught by the CI.

2023-01-26 21:36 UTC, dalg24 commented
What compilers are warning?  I would have sworn AppleClang did not yell at me...

2023-01-26 21:44 UTC, masterleinad commented
> What compilers are warning? I would have sworn AppleClang did not yell at me...

`Apple clang version 14.0.0 (clang-1400.0.29.202)` complained for me

2023-01-27 02:31 UTC, PhilMiller commented
To be clear, the warnings arose because we `[[deprecated]]` `Kokkos::Impl::ALL_t`, and so stuff in that namespace sees the deprecated name and not the non-deprecated public name?

2023-01-27 03:36 UTC, masterleinad commented
> To be clear, the warnings arose because we `[[deprecated]]` `Kokkos::Impl::ALL_t`, and so stuff in that namespace sees the deprecated name and not the non-deprecated public name?

Yes, but, of course, it referred to `Kokkos::Impl::ALL_t` all the time. Deprecating it didn't change that. 🙂

2023-01-29 02:25 UTC, dalg24 commented
I'd rather drop the [[deprecated]] attribute than qualify everywhere.

2023-01-30 13:43 UTC, dalg24 requested changes
Add a comment by the deprecated alias to cleanup and remove our qualifying Kokkos::ALL_t when we remove the alias.
Drop the changes to .jenkins.

2023-01-30 14:33 UTC, dalg24 approved these changes

2023-01-30 17:43 UTC, crtrott approved these changes

2023-01-30 17:43 UTC, merged