Fix warning in some user code when using std::memcpy
kokkos/kokkos pull request #6000
Opened 2023-03-20 13:50 UTC by Rombur

This should fix the warning seen by user in https://github.com/kokkos/kokkos/issues/5998

2023-03-20 22:48 UTC, nliber requested changes

2023-03-20 22:48 UTC, nliber commented on core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
> +    std::memcpy((void *)staging, (void *)&driver, sizeof(DriverType));
We should use C++ casts and be const correct (as the C-style cast on `&driver` isn't), as in
```c++
std::memcpy(static_cast<void*>(staging), static_cast<const void*>(&driver), sizeof(driver));
```

2023-03-24 14:02 UTC, dalg24 approved these changes

2023-03-24 20:17 UTC, nliber approved these changes

2023-03-24 20:21 UTC, dalg24 commented
clang-format accident :)

2023-03-28 01:23 UTC, merged

2023-03-28 01:25 UTC, dalg24 commented
Please cherry-pick into 4.0.01 patch release

2023-03-29 20:02 UTC, crtrott commented
Is this a problem in 3.7? I don't think so or? @Rombur Please cherry-pick to 4.0.01

2023-03-29 20:21 UTC, Rombur commented
It's not a problem in 3.7