Changelog 4.0.0/team thread sort
kokkos/kokkos pull request #6007
Opened 2023-03-22 20:32 UTC by ajpowelsnl

This PR simply adds #5317 as an item to the Kokkos-4.0.0 CHANGELOG.  This item will be featured in the upcoming Demo.

2023-03-22 20:43 UTC, masterleinad commented
Surely, you didn't mean to add 446 commits. 🙂

2023-03-22 21:03 UTC, ajpowelsnl commented
> Surely, you didn't mean to add 446 commits. 🙂

Correct.

2023-03-22 21:47 UTC, dalg24 commented
PR must target the `develop` branch

2023-03-22 22:42 UTC, dalg24 reviewed
Please use `[ci skip]` in your commit message

2023-03-22 22:42 UTC, dalg24 commented on CHANGELOG.md
> +- Team- and Thread-level sort, sort_by_key.  The interfaces to sort_[team/thread] and sort_by_key[team/thread] are designed to be similar to Thrust, except they take Kokkos::Views and not iterators.
```suggestion
- Add team- and thread-level `sort` and `sort_by_key` algorithms. [\#5317](https://github.com/kokkos/kokkos/pull/5317)
```

2023-03-24 20:29 UTC, dalg24 requested changes
Still targeting the wrong branch

2023-03-30 16:06 UTC, crtrott commented
You can't change master anymore, this probably should be a fix in the patch release 4.0.01

2023-04-05 14:14 UTC, masterleinad commented
@ajpowelsnl ping

2023-04-05 15:21 UTC, ajpowelsnl commented
> You can't change master anymore, this probably should be a fix in the patch release 4.0.01

I'll add #6007 to the 4.0.01 CHANGELOG

2023-04-09 12:11 UTC, dalg24 commented
@ajpowelsnl Your PR is against the master branch instead of develop.  Please fix it.

2023-04-11 15:46 UTC, masterleinad commented
@ajpowelsnl ping

2023-04-11 19:37 UTC, ajpowelsnl commented
Close b/c needs to be on `develop`

2023-04-26 20:34 UTC, dalg24 commented
Would need to target 4.0.01 and is probably too late
cc @ndellingwood

2023-05-05 21:50 UTC, closed without merging