Use -Wextra in CI
kokkos/kokkos pull request #6016
Opened 2023-03-28 01:40 UTC by masterleinad

Just for checking fallout in CI.

2023-03-29 22:45 UTC, masterleinad commented on core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp
> +      base_t::m_functor_reducer.get_reducer().init(base_t::m_result_ptr);
This is related to the changes for `StdPartitionCopyScalar`.

2023-03-30 12:49 UTC, dalg24 requested changes
Please split it up

2023-04-04 19:44 UTC, masterleinad commented on core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
> +  static uint64_t m_lock_size;
```
/tmp/kokkos/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.cpp:121:19: error: comparison of integers of different signs: 'int64_t' (aka 'long long') and 'unsigned long' [-Werror,-Wsign-compare]
  if (m_lock_size < (lock_array_elem * sizeof(int))) {
      ~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

2023-04-05 14:57 UTC, masterleinad commented
Retest this please.

2023-04-10 16:45 UTC, dalg24 commented on containers/src/Kokkos_OffsetView.hpp
> +    for (size_t i = 0; i != arg_rank; ++i) {
What about that warning?  Shadowing?  I thought these were already enabled.

2023-04-10 16:58 UTC, masterleinad commented on core/src/Kokkos_View.hpp
> +  static constexpr unsigned rank_dynamic = dimension::rank_dynamic;
The relevant warnings were about comparing enums with non-enums.

2023-04-10 18:51 UTC, Rombur approved these changes

2023-04-11 07:12 UTC, rgayatri23 approved these changes

2023-04-12 18:09 UTC, merged