Fix namespace for is_device_copyable
kokkos/kokkos pull request #6017
Opened 2023-03-28 15:32 UTC by masterleinad

We forgot to prefix `is_device_copyable` with `sycl` in https://github.com/kokkos/kokkos/pull/6009/commits/3d48d63e73667ad416c8cd75614f476438132291. The CI didn't catch it because the branch using `is_device_copyable` is not used for `SYCL+Cuda`.

2023-03-28 15:43 UTC, dalg24 approved these changes

2023-03-28 16:08 UTC, masterleinad commented
edit: I also enabled `is_device_copyable` for `SYCL+Cuda`.

2023-03-28 16:29 UTC, nliber approved these changes

2023-03-28 17:22 UTC, masterleinad commented
> Please update the title line to reflect this.

Here you go.

2023-03-28 18:02 UTC, dalg24 commented
Test this please

2023-03-28 19:40 UTC, dalg24 requested changes
SYCL build failed

2023-03-28 20:03 UTC, masterleinad commented
> SYCL build failed

🙁 Well, let's then just fix the bug. At least, the failing tests look fixable.

2023-03-29 19:49 UTC, dalg24 approved these changes

2023-03-29 19:49 UTC, merged