Add half precision math functions
kokkos/kokkos pull request #6045
Opened 2023-04-11 14:16 UTC by e10harvey

Related to https://github.com/kokkos/kokkos-kernels/pull/1774.

TODO: 
- [ ]  "Kokkos::abs" matches the argument list
- [ ]  "Kokkos::imag" matches the argument list
- [ ]  "Kokkos::isinf" matches the argument list
- [ ]  "Kokkos::isnan" matches the argument list
- [ ]  "Kokkos::pow" matches the argument list
- [ ]  "Kokkos::real" matches the argument list
- [ ]  "Kokkos::abs" matches the argument list
- [ ]  "Kokkos::imag" matches the argument list
- [ ]  "Kokkos::isinf" matches the argument list
- [ ]  "Kokkos::isnan" matches the argument list
- [ ]  "Kokkos::pow" matches the argument list
- [ ]  "Kokkos::real" matches the argument list

2023-04-11 14:30 UTC, dalg24 requested changes
These need to be added to the <Kokkos_Half.hpp> header

2023-04-12 13:44 UTC, lucbv reviewed
It looks fine to me just a couple clean ups needed

2023-04-12 13:44 UTC, lucbv commented on core/src/Kokkos_Half.hpp
> +//#include <Kokkos_MathematicalFunctions.hpp>
Looks like this can be removed

2023-04-12 13:44 UTC, lucbv commented on core/src/Kokkos_Half.hpp
> +/// bit index:   15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0
Looks like you need an extra space somewhere to align this properly?
If it looks good in the documentation then its fine.

2023-04-12 15:16 UTC, dalg24 commented on core/src/Kokkos_Half.hpp
> +  static constexpr int value = 0x7C00;
Please add the missing numerics trait in a separate PR

2023-04-12 15:16 UTC, dalg24 commented on core/src/Kokkos_Half.hpp
> +KOKKOS_INLINE_FUNCTION Kokkos::Experimental::half_t imag([[maybe_unused]] Kokkos::Experimental::half_t x) {
```suggestion
KOKKOS_INLINE_FUNCTION Kokkos::Experimental::half_t imag(Kokkos::Experimental::half_t) {             
```

2023-04-12 15:16 UTC, dalg24 commented on core/src/Kokkos_Half.hpp
> +    using KOKKOS_IMPL_MATH_FUNCTIONS_NAMESPACE::FUNC;             \
If you are going to cast to float then defer to Kokkos::FUNC

2023-04-12 15:16 UTC, dalg24 commented on core/src/Kokkos_Half.hpp
> +        FUNC(static_cast<float>(x)));                             \
```suggestion
    return static_cast<Kokkos::Experimental::half_t>(             \
        Kokkos::FUNC(static_cast<float>(x)));                             \
```
(not formatted)

2023-04-12 15:16 UTC, dalg24 commented on core/src/Kokkos_Half.hpp
> +  KOKKOS_INLINE_FUNCTION Kokkos::Experimental::half_t FUNC##fp16( \
Please comment about the suffixed versions that are being added.
Is there prior practice of using that suffix?  Do we need/want them?

2023-04-12 15:28 UTC, crtrott requested changes
I also think we should split the file, into non-public subfiles and then include them all in Kokkos_Half.hpp

2023-04-12 15:28 UTC, crtrott commented on core/src/Kokkos_Half.hpp
> +    using KOKKOS_IMPL_MATH_FUNCTIONS_NAMESPACE::FUNC;             \
Not needed, just call Kokkos::FUNC, after all you anyway call the float version.

2023-04-12 15:28 UTC, crtrott commented on core/src/Kokkos_Half.hpp
> +  KOKKOS_INLINE_FUNCTION Kokkos::Experimental::half_t FUNC##fp16( \
We probably shouldn't provide these: there is no clear convention for this (for example NVIDIA has hexp not exp_fp16, and uses hexp for both half and bhalf. So lets leave this overload out.

2023-04-19 17:47 UTC, cwpearson approved these changes

2023-04-21 19:39 UTC, masterleinad approved these changes
Looks OK to me.

2023-04-24 19:16 UTC, e10harvey commented
@dalg24, @crtrott: Ready to merge?

2023-04-24 19:44 UTC, dalg24 commented
> @dalg24, @crtrott: Ready to merge?

How does it relate to #6055 ?
There is no proper description and we are back to one large PR that does things can/should be separated out.

2023-04-24 19:51 UTC, e10harvey commented
> > 
> 
> How does it relate to #6055 ?

Good question. This is simply related to 6055 in that the traits and infinity-helper were requested to be put in a separate PR (which is now 6055).

> There is no proper description and we are back to one large PR that does things can/should be separated out.

I am not sure I follow. The original motivation for this PR was to add the half-precision math functions and during review it was requested that the traits and math fns be moved into separate headers. Are you saying you want 3 PRs:
1. Move the floating_point_wrapper to a private header file
2. Move half traits to a private header file
3. Add half math fns to a private header file

If so, that's no problem. I can create 3 PRs.

2023-04-24 23:25 UTC, crtrott requested changes
I think we can do the mathematical functions simpler or? Otherwise looks ok.

2023-04-24 23:25 UTC, crtrott commented on core/src/impl/Kokkos_Half_MathematicalFunctions.hpp
> +
Is there any reason not to do half_t and bhalf_t in one go if both are available? Are there any math functions which don't work in both cases?

```c++
#define KOKKOS_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE(FUNC, TYPE)          \
  KOKKOS_INLINE_FUNCTION TYPE FUNC( TYPE x)                          \
    { return static_cast<TYPE>(  Kokkos::FUNC(static_cast<float>(x)));  }
    
#if defined(KOKKOS_HALF_T_IS_FLOAT) && !KOKKOS_HALF_T_IS_FLOAT
  #if defined(KOKKOS_BHALF_T_IS_FLOAT) && !KOKKOS_BHALF_T_IS_FLOAT
    #define KOKKOS_IMPL_MATH_UNARY_FUNCTION_HALF(FUNC) \
            KOKKOS_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE(FUNC, Kokkos::Experimental::half_t) \
            KOKKOS_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE(FUNC, Kokkos::Experimental::bhalf_t)
  #else
    #define KOKKOS_IMPL_MATH_UNARY_FUNCTION_HALF(FUNC) \
         KOKKOS_IMPL_MATH_UNARY_FUNCTION_HALF_TYPE(FUNC, Kokkos::Experimental::half_t)
  #endif
#endif
```

This way we won't overlook any instantiation.

2023-04-24 23:25 UTC, crtrott commented on core/src/impl/Kokkos_Half_MathematicalFunctions.hpp
> +}
In this case abs isn't different from the other Unary is it? Abs is a special case on the underlying math functions due to the way how abs is part of the pure integer stuff and the cmath in the standard, but it is not here a special case or?

2023-05-01 15:26 UTC, e10harvey commented
@crtrott, @dalg24: I think I addressed your feedback. The CI failure in SYCL is unrelated to these changes. Ready to merge?

2023-05-01 17:10 UTC, dalg24 commented
> @crtrott, @dalg24: I think I addressed your feedback. The CI failure in SYCL is unrelated to these changes. Ready to merge?

As far as I am concerned no.  My objections are there is no proper description (you need to edit) and this patch is doing 3 things that really should be split up in 3 PRs.  I am not blocking if Christian decides your last changes addressed his concerns and he wants to merge.

At the moment you have two stales approval (approvals but for a version of the patch that is significantly out of date) and one request changes.  There is not enough consensus to merge yet.

2023-05-10 19:09 UTC, e10harvey commented
Closing. Please review https://github.com/kokkos/kokkos/pull/6055. I will open 2 more PRs -- one for moving floating point wrapper to a private header and another for the half math functions.

2023-05-10 19:09 UTC, closed without merging