core/src: Move half traits to private header
kokkos/kokkos pull request #6055
Opened 2023-04-13 15:20 UTC by e10harvey

- Add infinity trait
  
  Related to #6045 and https://github.com/kokkos/kokkos-kernels/pull/1774.

2023-04-13 20:18 UTC, dalg24 reviewed
Please update the title line of your PR and make sure it mentions this is adding the half precision specializations of the infinity traits that were missing.
This is the most relevant of your PR because that is the only part that is meant to be observable by the user.

2023-04-13 20:18 UTC, dalg24 commented on core/src/Kokkos_Half_NumericTraits.hpp
If as the title line of your PR suggest this header is intended to be a private header, it is probably better to move it to the impl/ subdirectory.

2023-04-13 20:29 UTC, dalg24 approved these changes

2023-04-13 20:31 UTC, dalg24 commented on core/src/impl/Kokkos_Half_NumericTraits.hpp
> +struct Kokkos::Experimental::Impl::infinity_helper<Kokkos::Experimental::half_t> {
you are relying on transitive includes for `half_t`

2023-05-08 22:48 UTC, nliber approved these changes

2023-05-09 17:45 UTC, masterleinad requested changes
Please split the one commit in such a way that one commit solely moves code without changing anything and other commits fix typos and add stuff. Otherwise, it is very hard to see what the real changes in this pull request are.

2023-05-10 20:38 UTC, dalg24 commented
Just posting it here in case it saves some time to other reviewers
The 1st commit is not per se a move (I pasted the diff below) but I suppose it is ok.  `develop` has comments about the infinity trait and the actual implementation had been lost somewhere in translation.
```diff
--- develop
+++ this_pr
@@ -39,17 +39,7 @@
 //           2**15 * (1 + 0.9990234375) =
 //           65504.0
 //
-
-/// \brief: Infinity.
-///
-/// base2 encoding: bits [10,14] set
-/// #define KOKKOS_IMPL_HALF_T_HUGE_VALH 0x7c00
-/// Binary16 encoding:
-///             [s  e  e  e  e  e  f f f f f f f f f f]
-///             [0  1  1  1  1  1  0 0 0 0 0 0 0 0 0 0]
-/// bit index:  15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0
 #if defined(KOKKOS_HALF_T_IS_FLOAT) && !KOKKOS_HALF_T_IS_FLOAT
-
 /// \brief: Minimum normalized number
 ///
 /// Stdc defines this as the smallest number (representable in binary16).
@@ -194,7 +184,7 @@

 /// \brief: This is the smallest possible exponent value
 ///
-/// Stdc defines this as the smallest possible exponent value for type binary16.
+/// Stdc defines this as the smallest possible exponent val`ue for type binary16.
 /// More precisely, it is the minimum negative integer such that the value min_exponent_helper
 /// raised to this power minus 1 can be represented as a normalized floating point number of type float.
 ///
@@ -309,4 +299,4 @@
   static constexpr int value = 128;
 };
 #endif
-////////////// END BHALF_T (bfloat16) limits //////////////
+////////////// END BHALF_T (bfloat16) limits //////////
```

Please expand the description.  Say something like:
```
This PR does 2 things
* move the numeric traits specializations for `half_t` and `bhalf_t` to a new `<core/src/impl/Kokkos_Half_NumericTraits.hpp>` header
* add the infinity trait for the half types that was missing (oversight)
```

2023-05-10 20:39 UTC, dalg24 commented on core/src/impl/Kokkos_Half_NumericTraits.hpp
> +/// Stdc defines this as the smallest possible exponent val`ue for type binary16.
Fix the typo that was introduced in the splitting header up
```suggestion
/// Stdc defines this as the smallest possible exponent value for type binary16. 
```

2023-05-10 20:44 UTC, masterleinad approved these changes
Looks OK to me now (pending Damien's comments).

2023-05-14 14:43 UTC, dalg24 commented
Failures are unrelated (HIP build timing out)
Counting Daniel's approval which is not showing since a new review was requested.

2023-05-14 14:43 UTC, dalg24 approved these changes

2023-05-14 14:43 UTC, merged