Update changelog
kokkos/kokkos pull request #6058
Opened 2023-04-14 09:54 UTC by cz4rs

Update changelog for the release 4.0.01.

fixes https://github.com/kokkos/kokkos/issues/5903

2023-04-14 11:34 UTC, dalg24 approved these changes

2023-04-14 11:37 UTC, dalg24 commented on CHANGELOG.md
> +[Full Changelog](https://github.com/kokkos/kokkos/compare/4.0.0...4.0.01)
```suggestion
[Full Changelog](https://github.com/kokkos/kokkos/compare/4.0.00...4.0.01)
```

2023-04-14 11:38 UTC, dalg24 commented on CHANGELOG.md
>  [Full Changelog](https://github.com/kokkos/kokkos/compare/3.7.01...4.0.0)
```suggestion
[Full Changelog](https://github.com/kokkos/kokkos/compare/3.7.01...4.0.00)
```

2023-04-14 11:39 UTC, dalg24 requested changes
URL to get the full change log is wrong

2023-04-21 16:58 UTC, ndellingwood approved these changes

2023-04-26 20:08 UTC, merged