eam-level std algos: part 7 of N
kokkos/kokkos pull request #6211
Opened 2023-06-12 14:16 UTC by fnrizzi

Co-authored-by: Cezary Skrzyński
Co-authored-by: Jakub Strzebonski

2023-08-31 19:57 UTC, Rombur approved these changes

2023-09-06 09:44 UTC, fnrizzi commented
CI failure unrelated:
```
The following tests FAILED:
	 37 - Kokkos_PerformanceTest_Benchmark (Timeout)
Errors while running CTest
```

2023-09-06 16:49 UTC, crtrott requested changes

2023-09-06 16:49 UTC, crtrott commented on algorithms/src/std_algorithms/impl/Kokkos_ShiftLeft.hpp
> +  }
this needs to be a Kokkos::single

2023-09-06 16:49 UTC, crtrott commented on algorithms/src/std_algorithms/impl/Kokkos_ShiftRight.hpp
> +  }
needs to be a Kokkos::single

2023-09-06 17:56 UTC, crtrott approved these changes

2023-09-07 00:09 UTC, fnrizzi commented
unrelated Openmptarget failure:
```
The following tests FAILED:
	  4 - Kokkos_CoreUnitTest_OpenMPTarget (Failed)
```	  
and hpx 
```
The following tests FAILED:
	  4 - Kokkos_CoreUnitTest_HPX (Timeout)
```

2023-09-07 02:08 UTC, merged