Fix AVX2 simd support for ZEN2 AMD CPU.
kokkos/kokkos pull request #6238
Opened 2023-06-23 11:51 UTC by pkestene

Enable AVX2 vectorization when KOKKOS_ARCH_AMD_AVX2 is ON

2023-06-23 11:53 UTC, dalg24 requested changes

2023-06-23 11:53 UTC, dalg24 commented on simd/src/Kokkos_SIMD.hpp
> +#if definded(KOKKOS_ARCH_AVX2) || defined(KOKKOS_ARCH_AMD_AVX2)
```suggestion
#if defined(KOKKOS_ARCH_AVX2) || defined(KOKKOS_ARCH_AMD_AVX2)
```

2023-06-23 13:09 UTC, masterleinad approved these changes

2023-06-23 19:11 UTC, ldh4 approved these changes

2023-06-23 19:16 UTC, Rombur commented
Is there a reason why we don't use `KOKKOS_ARCH_AVX2` on AMD CPU?

2023-06-26 15:25 UTC, dalg24 approved these changes

2023-06-26 15:35 UTC, masterleinad approved these changes

2023-06-26 15:37 UTC, ldh4 approved these changes

2023-06-26 16:49 UTC, dalg24 commented
Retest this please

2023-06-26 22:11 UTC, merged