[WIP] #5635: HIP: Add Overloads for parallel_scan with return value
kokkos/kokkos pull request #6242
Opened 2023-06-27 11:21 UTC by thearusable

Related to #5635

2023-07-07 15:27 UTC, masterleinad requested changes
Please avoid copying the implementation from the overloads not returning the total.

2023-07-12 10:05 UTC, thearusable commented
> Why does this pull request also touch `Cuda`?

I created the PRs as a chain which should be merged in particular order. This one is the last one currently created so it contains the changes from other ones. There will be at least two more PRs created.

2023-08-09 21:19 UTC, masterleinad commented
Marking as draft since dependencies have not been merged.

2023-09-27 12:47 UTC, masterleinad approved these changes

2023-09-27 18:32 UTC, cz4rs commented on core/src/HIP/Kokkos_HIP_Team.hpp
> +      closure(i - 1, val, false);
See the discussion https://github.com/kokkos/kokkos/pull/6235#discussion_r1331460296 for a similar fix in CUDA backend.

2023-09-28 09:30 UTC, fnrizzi approved these changes

2023-09-28 09:30 UTC, fnrizzi commented
gcc timed out , rest passes

2023-10-02 14:05 UTC, Rombur commented on core/unit_test/TestTeamVector.hpp
> +#if !defined(KOKKOS_IMPL_CUDA_CLANG_WORKAROUND)
If it works for HIP and CUDA nvcc, there is a high probability that it also works for CUDA clang. Not for this PR but I think it's worth to check if the still need this condition.

2023-10-02 14:06 UTC, Rombur approved these changes

2023-10-04 17:42 UTC, crtrott approved these changes

2023-10-04 17:42 UTC, merged