[SYCL][Reduction] Group counter should use at least memory_order::acq_rel
kokkos/kokkos pull request #6430
Opened 2023-09-11 21:18 UTC by aelovikov-intel

From https://en.cppreference.com/w/cpp/atomic/memory_order:

> Atomic operations tagged memory_order_relaxed are not synchronization
> operations; they do not impose an order among concurrent memory
> accesses. They only guarantee atomicity and modification order
> consistency.

Yet we want to use that counter exactly for the synchronization purposes - to decide which WG finished last and should perform the final step.

The same issue had been fixed in DPC++ at https://github.com/intel/llvm/pull/8058.

2023-09-11 21:24 UTC, masterleinad submitted a review, later dismissed
Looks reasonable.

2023-09-11 21:24 UTC, masterleinad commented
OK to test.

2023-09-11 22:24 UTC, dalg24 reviewed
What about this one
https://github.com/kokkos/kokkos/blob/9081d366c4a67a5900a512993cfd79a884b73674/core/src/SYCL/Kokkos_SYCL_ParallelScan_Range.hpp#L182-L186

2023-09-11 22:33 UTC, dalg24 commented
Also I don't get it.
Consider
https://github.com/kokkos/kokkos/blob/9081d366c4a67a5900a512993cfd79a884b73674/core/src/SYCL/Kokkos_SYCL_ParallelReduce_Team.hpp#L211-L215
which this PR suggest to change to use `memory_order::acq_rel`.
Why is relaxed not sufficient?  We only atomic increment of the counter.

2023-09-11 22:36 UTC, dalg24 commented
It is not like with relaxed ordering will break https://github.com/kokkos/kokkos/blob/9081d366c4a67a5900a512993cfd79a884b73674/core/src/SYCL/Kokkos_SYCL_ParallelReduce_Team.hpp#L218
What am I missing?

2023-09-11 22:41 UTC, crtrott requested changes
I think this is unnecessary. I am pretty sure this is not needed at all, and the previous memory order was sufficient for the use case here.

2023-09-11 22:49 UTC, aelovikov-intel commented
> It is not like with relaxed ordering will break

That's exactly what happens - we see random failures on 
```core/unit_test/Kokkos_CoreUnitTest_SYCL1B --gtest_filter=sycl.mdrange_parallel_reduce_primitive_types```
when running on one of our Intel GPUs. Corresponding issue in DPC++ was reported by one of the IGC (https://github.com/intel/intel-graphics-compiler) developers. What I was told is that `relaxed` ordering only requires the atomic counter to be synced between the threads, but not the actual reduction data. Having `acq_rel` results in the compiler emitting extra fences syncing the memory.

Another quote from the https://en.cppreference.com/w/cpp/atomic/memory_order:

> Release-Acquire ordering
> If an atomic store in thread A is tagged memory_order_release, an atomic load in thread B from the same variable is tagged memory_order_acquire, and the load in thread B reads a value written by the store in thread A, then the store in thread A synchronizes-with the load in thread B.
>
> All memory writes (including non-atomic and relaxed atomic) that happened-before the atomic store from the point of view of thread A, become visible side-effects in thread B.

We need this synchronization of the whole memory, not just the atomic counter that is being incremented, to be visible across all WGs.

2023-09-15 16:21 UTC, crtrott commented
We came to the conclusion that this (or something similar) is required.

2023-09-15 16:57 UTC, masterleinad approved these changes
Since this has passed testing already, let's move forward with this approach.

2023-10-11 20:41 UTC, crtrott approved these changes

2023-10-11 20:41 UTC, merged