fix impl
kokkos/kokkos pull request #6493
Opened 2023-10-09 14:09 UTC by fnrizzi

2023-10-10 00:20 UTC, nliber requested changes

2023-10-10 00:20 UTC, nliber commented on algorithms/src/std_algorithms/impl/Kokkos_MustUseKokkosSingleInTeam.hpp
> +struct stdalgo_must_use_kokkos_single_for_team_scan : std::false_type {};
Add and use:

```c++
template<typename T>
inline constexpr bool stdalgo_must_use_kokkos_single_for_team_scan_v = stdalgo_must_use_kokkos_single_for_team_scan<T>::value;
```

to match the C++17 type traits.

2023-10-11 18:16 UTC, nliber approved these changes

2023-10-11 18:23 UTC, crtrott approved these changes

2023-10-11 18:25 UTC, merged