readme: Update README.md
kokkos/kokkos pull request #6512
Opened 2023-10-16 10:54 UTC by eltociear

github -> GitHub

2023-10-16 15:17 UTC, crtrott requested changes
This needs to go against develop not master.

2023-10-16 15:19 UTC, dalg24 commented
No need to run the CI...
And yes please open against the `develop` branch.

2023-10-17 11:50 UTC, fnrizzi commented
probably easier to just make a new PR :)

2023-10-19 22:50 UTC, dalg24 approved these changes

2023-10-19 22:52 UTC, ldh4 approved these changes

2023-10-19 22:53 UTC, merged