Partial fix to compile time issues w/nvcc + Kokkos_ENABLE_DEBUG_BOUNDS_CHECK
kokkos/kokkos pull request #6596
Opened 2023-11-13 22:28 UTC by weinbe2

This is a partial fix to the compile-time issues noted in #6325 . In particular, `Kokkos_CoreUnitTest_Default` now compiles in a reasonable amount of time with `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK` defined. However, some other unit tests not noticed in that issue still have compile-time woes. This is a point of further investigation.

2023-11-13 22:51 UTC, masterleinad reviewed
I guess the main difference make using `__noinline__` vs `inline`?

2023-11-14 15:42 UTC, weinbe2 commented on core/src/Cuda/Kokkos_Cuda_abort.hpp
> +__device__ __noinline__ [[noreturn]] static  void cuda_abort(const char *const message) {
Unsure on this one, actually, I didn't think too critically about pre-Volta (despite the comment, which is sloppy on my part). The more ideal solution here would likely be an `ifdef` guard on it being Pascal/earlier as opposed to a broader hammer. If it's still there, my guess is the problem stems from how Volta+ has "threads are threads" while Pascal- doesn't, so an "abort" on some threads in a warp but not other could cause a hang.

2023-11-14 15:46 UTC, weinbe2 commented
> I guess the main difference make using `__noinline__` vs `inline`?

The overall difference is keeping the compiler from wasting time on code it can never reach, which both `[[noreturn]]` and to a degree `__noinline__` helps with. Removing `inline` also means that you can add `static`.

2023-11-14 16:43 UTC, masterleinad commented on core/src/Cuda/Kokkos_Cuda_abort.hpp
> +__device__ __noinline__ [[noreturn]] static  void cuda_abort(const char *const message) {
Can you check on a `Pascal` architecture?

2023-11-14 18:31 UTC, rgayatri23 commented
When you say partial fix, are you referring to the 25% increase in compile time that we still observe when `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK` is `ON` ?

2023-11-14 20:38 UTC, weinbe2 commented
> When you say partial fix, are you referring to the 25% increase in compile time that we still observe when `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK` is `ON` ?

At a high level, yes. It fixes `Kokkos_CoreUnitTest_Default` in particular, but there are other tests that still show slowdowns when that flag is `ON`.

2023-11-18 17:16 UTC, crtrott requested changes
Blocking until we tested on pre-volta

2023-11-21 17:45 UTC, weinbe2 commented
> Blocking until we tested on pre-volta

It's a WIP. There's a test when I do a full compile that's taking "forever" to compile for `sm_60` some reason, and I haven't had the cycles to figure out what's going on quite yet. It isn't the RNG test, though, so I can try to narrowly compile that.

2024-04-22 19:04 UTC, ajpowelsnl commented
@weinbe2 , @masterleinad -- would you please have a look at the CI failures ?  Also, is testing on Pascale architectures still needed before we merge?

2024-05-06 17:59 UTC, ajpowelsnl commented
**TODO:**
- Rebase
- Do compile time test on pre-Volta architectures
- Fix CI issues

2024-05-16 00:54 UTC, nmm0 commented
This PR has been rebased and put on a different branch here: https://github.com/kokkos/kokkos/pull/7013

2024-05-16 00:54 UTC, closed without merging