Fixe the too-much-OpenACC-warning issue
kokkos/kokkos pull request #6643
Opened 2023-12-01 16:00 UTC by seyonglee

This PR fixes the too-much-OpenACC-warning issue, mentioned in PR #6639.
This PR also re-enables the OpenACC CI test.

2023-12-01 16:07 UTC, masterleinad requested changes
Changes to `desul` should be merged to https://github.com/desul/desul/ first.

2023-12-01 19:29 UTC, seyonglee commented
> Changes to `desul` should be merged to https://github.com/desul/desul/ first.

A new `desul` PR (https://github.com/desul/desul/pull/119) containing the same changes except for the OpenACC CI change is submitted.

2023-12-01 20:25 UTC, masterleinad approved these changes

2023-12-02 02:44 UTC, seyonglee commented on tpls/desul/include/desul/atomics/Compare_Exchange_OpenACC.hpp
> +          "the OpenACC backend\n");
Yes, it will be executed non-atomically, which will be OK  for the serial backend on the host.

2023-12-04 20:43 UTC, Rombur approved these changes

2023-12-04 20:43 UTC, Rombur commented
Retest this please

2023-12-06 16:22 UTC, merged