Don't disable desul atomics is only the Serial backend is enabled
kokkos/kokkos pull request #6672
Opened 2023-12-14 16:21 UTC by masterleinad

The tests in https://github.com/kokkos/kokkos/pull/6151 (in particular the Windows build, as well as `ThreadSanitizer` and `AddressSanitizer`) show that we need to use proper atomics for at least `HostSharedPointer` and `SharedAllocationRecord` even in the case that only the `Serial` backend is enabled if multiple threads are used.
This pull request proposes to just remove the special handling of this case to avoid other hard-to-find bugs.
The alternative is, of course, to just fix the two classes mentioned above.

2023-12-14 18:28 UTC, dalg24 commented
You are free to investigate how to resolve the race conditions in the unit test but know that this is a much bigger discussion.
I would tend to agree with you, even more so in the context of multiple serial execution space instances but this is in-place because atomics where prohibitively expensive for some downstream who didn't want to do atomic-if-needed in their functors.

2023-12-14 18:31 UTC, crtrott requested changes
At a minimum we need an option to enable the current behavior with Serial only. Long term (i.e. Kokkos 5) we could talk to apps to explicitly do this on their side by directly using desul atomics with proper scope.

2023-12-14 23:11 UTC, masterleinad commented
Let's make this a draft for now and first fix the relevant spots in #6674.

2024-01-04 18:15 UTC, masterleinad commented
Superseded by #6692.

2024-01-04 18:15 UTC, closed without merging