WIP: separate iterators from algorithms, move iterators into core
kokkos/kokkos pull request #6684
Opened 2023-12-20 22:10 UTC by fnrizzi

2025-11-04 19:34 UTC, janciesko commented
Squashed and rebased. I've updated the title.

2026-05-07 23:49 UTC, ldh4 reviewed
I think this is a nice refactor. Moving `RandomAccessIterator` out of `algorithms` along with its public interface sounds intuitive.

No strong opinion on the file name `Kokkos_Iterator`. It describes what it is. Just need to clearly communicate that `Kokkos_Iterator` is not intended to be the kokkos implementation of the `Iterator` lib.

> TODO TO FINISH
> - move tests

Is this going to be handled as part of this PR?

2026-05-08 17:13 UTC, masterleinad commented
```
[C++20-Modules-Clang-19] In file included from /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/Kokkos_StdAlgorithms.cppm:6:
[C++20-Modules-Clang-19] In file included from /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/Kokkos_StdAlgorithms.hpp:18:
[C++20-Modules-Clang-19] In file included from /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/std_algorithms/Kokkos_IterSwap.hpp:13:
[C++20-Modules-Clang-19] /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:75:7: error: missing '#include "Kokkos_Iterator.hpp"'; 'are_random_access_iterators' must be declared before it is used
[C++20-Modules-Clang-19]    75 |       are_random_access_iterators<IteratorTypes...>::value,
[C++20-Modules-Clang-19]       |       ^
[C++20-Modules-Clang-19] /var/jenkins/workspace/Kokkos_PR-6684/core/src/Kokkos_Iterator.hpp:78:8: note: declaration here is not visible
[C++20-Modules-Clang-19]    78 | struct are_random_access_iterators;
[C++20-Modules-Clang-19]       |        ^
[C++20-Modules-Clang-19] In file included from /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/Kokkos_StdAlgorithms.cppm:6:
[C++20-Modules-Clang-19] In file included from /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/Kokkos_StdAlgorithms.hpp:18:
[C++20-Modules-Clang-19] In file included from /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/std_algorithms/Kokkos_IterSwap.hpp:13:
[C++20-Modules-Clang-19] /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:145:17: error: use of undeclared identifier 'is_iterator_v'
[C++20-Modules-Clang-19]   145 |   if constexpr (is_iterator_v<IteratorType1> && is_iterator_v<IteratorType2>) {
[C++20-Modules-Clang-19]       |                 ^
[C++20-Modules-Clang-19] /var/jenkins/workspace/Kokkos_PR-6684/algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp:145:49: error: use of undeclared identifier 'is_iterator_v'
[C++20-Modules-Clang-19]   145 |   if constexpr (is_iterator_v<IteratorType1> && is_iterator_v<IteratorType2>) {
[C++20-Modules-Clang-19]       |                                                 ^
[C++20-Modules-Clang-19] 3 errors generated.
```

2026-05-08 17:15 UTC, masterleinad commented
```
/home/runner/_work/kokkos/kokkos/kokkos/core/src/Kokkos_Iterator.hpp:83:27: error: use c++17 style variable templates [modernize-type-traits,-warnings-as-errors]
   83 |       is_iterator_v<T> && std::is_base_of<std::random_access_iterator_tag,
      |                           ^              
      |                                          _v
   84 |                                           typename T::iterator_category>::value;
      |                                                                         ~~~~~~~
63514 warnings generated.
```

2026-05-13 17:53 UTC, janciesko commented
> Is this going to be handled as part of this PR?

No. @ldh4

2026-05-13 18:19 UTC, janciesko commented
@masterleinad Should be ready.

2026-05-13 21:33 UTC, janciesko approved these changes

2026-05-13 22:16 UTC, masterleinad requested changes
Move the respective modules symbols to Kokkos_Core.cppm.

2026-05-14 17:46 UTC, janciesko commented
> Move the respective modules symbols to Kokkos_Core.cppm.

Done

2026-05-14 17:50 UTC, masterleinad commented on core/src/Kokkos_Core.cppm
> +  }  // namespace Impl
These symbolds belong to `Kokkos_Core_Impl.cppm` since they shouldn't be exposed to the user.

2026-05-14 18:20 UTC, janciesko commented on core/src/Kokkos_Core.cppm
> +  }  // namespace Impl
right, done

2026-05-14 19:18 UTC, masterleinad commented on core/src/Kokkos_Iterator.hpp
> +#endif
I can't see how this header can be standalone as-is and hence it can't be a public header
```suggestion
#ifndef KOKKOS_IMPL_PUBLIC_INCLUDE
#include <Kokkos_Macros.hpp>
static_assert(false,
              "Including non-public Kokkos header files is not allowed.");
#endif
```

2026-05-14 19:18 UTC, masterleinad commented on core/src/Kokkos_Iterator.hpp
> +#endif
```suggestion
```

2026-05-14 19:37 UTC, masterleinad approved these changes
Fine with me if it passes CI.

2026-05-14 21:51 UTC, ldh4 approved these changes
We should remember to update the documentation when this is merged.

2026-05-29 16:01 UTC, merged