std(remove-if): fixing tmp view alloc + avoid evaluating twice the predicate during final pass
kokkos/kokkos pull request #6747
Opened 2024-01-25 15:49 UTC by romintomasetti

2024-01-25 16:52 UTC, masterleinad commented on algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp
> +      if(is_final) {
```suggestion
      if(final_pass) {
```

2024-01-25 16:54 UTC, romintomasetti commented on algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp
> +      if(is_final) {
Indeed !

2024-01-25 16:55 UTC, romintomasetti commented on algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp
> +      if(is_final) {
Done.

2024-01-25 16:57 UTC, masterleinad approved these changes

2024-01-25 20:24 UTC, dalg24 approved these changes

2024-01-25 20:25 UTC, dalg24 commented
```diff
diff --git a/algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp b/algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp
index 850601fec..456df43ae 100644
--- a/algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp
+++ b/algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp
@@ -48,7 +48,7 @@ struct StdRemoveIfStage1Functor {
     auto& myval = m_first_from[i];

     if (!m_must_remove(myval)) {
-      if(final_pass) {
+      if (final_pass) {
         // calling move here is ok because we are inside final pass
         // we are calling move assign as specified by the std
         m_first_dest[update] = std::move(myval);
@@ -107,7 +107,9 @@ IteratorType remove_if_exespace_impl(const std::string& label,
     // create helper tmp view
     using value_type    = typename IteratorType::value_type;
     using tmp_view_type = Kokkos::View<value_type*, ExecutionSpace>;
-    tmp_view_type tmp_view(Kokkos::view_alloc(Kokkos::WithoutInitializing, ex, "std_remove_if_tmp_view"), keep_count);
+    tmp_view_type tmp_view(Kokkos::view_alloc(Kokkos::WithoutInitializing, ex,
+                                              "std_remove_if_tmp_view"),
+                           keep_count);
     using tmp_readwrite_iterator_type = decltype(begin(tmp_view));

     // in stage 1, *move* all elements to keep from original range to tmp

2024-01-25 20:26 UTC, dalg24 requested changes
Fix the format

2024-01-26 13:16 UTC, dalg24 approved these changes

2024-01-26 13:46 UTC, dalg24 commented
Not waiting for SYCL build that cannot find a machine to run

2024-01-26 13:46 UTC, merged