OpenMPTarget: Reverse loop order in MDRange.
kokkos/kokkos pull request #6925
Opened 2024-04-10 02:00 UTC by rgayatri23

The PR reverses the loop order for MDRange policy in the OpenMPTarget backend which is more performant for GPUs.

FYI - Tiling still gives wrong results in MDRange policy for the backend. Looking to fix it in a different PR later.

2024-04-11 18:13 UTC, rgayatri23 commented
> `MDRangePolicy` has outer and inner direction properties with backend-specific defaults but that can be overridden by the user. The default is up to the backend implementers but we need to see that the user choice is honored. You can look how we added support in the OpenACC backend (we still need to add support for tiles).

I addressed the issue. Separated the MDRange implementation into 2 files for `parallel_for` and `parallel_reduce`. Deleted the non-working and blocked tiling implementation for now. Will add it in a later PR.

2024-04-12 17:49 UTC, dalg24 approved these changes
Please update the title line and description to reflect what that PR does.

You might want to open an issue to track what is missing (e.g. support for non-sum reductions, etc.)
There is a lot of improvement/cleanup you can borrow from the OpenACC backend implementation (not asking you to do this here)

2024-04-12 17:49 UTC, dalg24 commented on core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_MDRange.hpp
> +#include <OpenMPTarget/Kokkos_OpenMPTarget_Parallel_Common.hpp>
What do you use from these headers?

2024-04-12 20:39 UTC, rgayatri23 commented on core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_MDRange.hpp
> +#include <OpenMPTarget/Kokkos_OpenMPTarget_Parallel_Common.hpp>
Nothing, I removed those.

2024-04-27 16:43 UTC, crtrott requested changes
What about having just one loop ordering you collapse but then make the index decisison in the middle:

```c++
if constexpr (std::is_same_v<Order,  OpenMPTargetIterateRight>) {
          if constexpr (std::is_void<typename Policy::work_tag>::value)
            functor(i0, i1, i2);
          else
            functor(typename Policy::work_tag(), i0, i1, i2);
        }
} else {
          if constexpr (std::is_void<typename Policy::work_tag>::value)
            functor(i2, i1, i0);
          else
            functor(typename Policy::work_tag(), i2, i1, i0);
        }
}
```
You need to also swap the loop bounds of course:

```c++
if constexpr (std::is_same_v<Order,  OpenMPTargetIterateRight>) {
    const Index begin_0 = policy.m_lower[0];
    const Index begin_1 = policy.m_lower[1];
    const Index begin_2 = policy.m_lower[2];

    const Index end_0 = policy.m_upper[0];
    const Index end_1 = policy.m_upper[1];
    const Index end_2 = policy.m_upper[2];
} else {
    const Index begin_0 = policy.m_lower[2];
    const Index begin_1 = policy.m_lower[1];
    const Index begin_2 = policy.m_lower[0];

    const Index end_0 = policy.m_upper[2];
    const Index end_1 = policy.m_upper[1];
    const Index end_2 = policy.m_upper[0];
}

2024-04-27 16:45 UTC, crtrott commented
Not 100% sure if its much cleaner what I suggested: Damien, Rahul?

2024-04-27 18:52 UTC, dalg24 commented
It’s elegant but would not work (bounds getting out of scope before the
tightly nested loops). I suppose you could declare the bounds before you
assign their value in the if constexpr or even use a ternary to initialize
them but at that point I think what we did in the OpenACC backend is more
readable.

On Sat, Apr 27, 2024 at 6:45 PM Christian Trott ***@***.***>
wrote:

> Not 100% sure if its much cleaner what I suggested: Damien, Rahul?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kokkos/kokkos/pull/6925#issuecomment-2081068605>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACIQETZZCVNDPH73XNKJULY7PI2RAVCNFSM6AAAAABF7STXJKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBRGA3DQNRQGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-04-28 15:51 UTC, crtrott approved these changes

2024-04-28 15:52 UTC, merged