Deprecate trailing `Proxy` template argument in `Kokkos::Array`
kokkos/kokkos pull request #6934
Opened 2024-04-11 21:53 UTC by dalg24

Following up on #6906 and deprecating the `Proxy` template argument in `Kokkos::Array<T, N, Proxy>`.

Rational:
* Further alignment with `std::array<T, N>`, `Kokkos::Array` is provided as a drop-in replacement for the facility provided by the standard library.  One caveat is we still spell it differently with that leading uppercase A...
* This rather obscure facility was solely there to support the view specialization that we removed in #6906.  We deprecate it instead of removing to be safe (I could not find any use when searching through Trilinos).  Doing so will reduce the code complexity and make it trivial to document `Kokkoss::Array` as we can just refer to the standard library documentation (we never bothered documenting it).

2024-04-12 13:18 UTC, masterleinad approved these changes

2024-04-15 16:15 UTC, nliber reviewed
Do we want to add a check in the primary template that `Proxy == void`, or is that overkill?

2024-04-15 16:16 UTC, nliber approved these changes

2024-04-15 16:48 UTC, dalg24 commented
> Do we want to add a check in the primary template that `Proxy == void`, or is that overkill?

Like `static_assert` or somehow emit a warning?
When would we raise that (for what config)?

2024-04-15 18:14 UTC, nliber requested changes
I don't think `<limits>` is used anywhere.

2024-04-15 19:48 UTC, dalg24 commented
> I don't think `<limits>` is used anywhere.

Not seeing how it relates to this PR.  Can you elaborate?

2024-04-15 20:36 UTC, nliber approved these changes

2024-04-15 21:08 UTC, merged