Work around MSVC+Cuda CI failure
kokkos/kokkos pull request #7068
Opened 2024-06-12 18:13 UTC by masterleinad

After the windows-2022 was updated in the GitHub runner we were seeing.

> C:\Program Files\NVIDIA GPU Computing
  Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189:
  #error: -- unsupported Microsoft Visual Studio version! Only the versions
  between 2017 and 2022 (inclusive) are supported! The nvcc flag
  '-allow-unsupported-compiler' can be used to override this version check;
  however, using an unsupported host compiler may cause compilation failure
  or incorrect run time execution.  Use at your own risk.
  [D:\a\kokkos\kokkos\build\CMakeFiles\3.29.3\CompilerIdCUDA\CompilerIdCUDA.vcxproj]

This pull request fixes that by updating Cuda to the latest available version in the action used for installing it.

2024-06-12 18:58 UTC, masterleinad commented
We are now getting error messages like
```
D:/a/kokkos/kokkos/core/src\Kokkos_View.hpp(976): error C2535: 'enable_if<Kokkos::Impl::always_true<I0,I1>::value&&2=='function'&&true&&false&&'function'==0,double&>::type Kokkos::View<double *,Kokkos::LayoutStride>::operator ()(I0,I1) const': member function already defined or declared [D:\a\kokkos\kokkos\build\algorithms\unit_tests\Kokkos_UnitTest_Sort.vcxproj]
  D:/a/kokkos/kokkos/core/src\Kokkos_View.hpp(954): note: see declaration of 'Kokkos::View<double *,Kokkos::LayoutStride>::operator ()'
  D:/a/kokkos/kokkos/core/src\Kokkos_View.hpp(976): note: the template instantiation context (the oldest one first) is
  D:/a/kokkos/kokkos/algorithms/unit_tests\TestStdAlgorithmsCommon.hpp(664): note: see reference to class template instantiation 'Kokkos::View<double *,Kokkos::LayoutStride>' being compiled
```

2024-06-12 19:36 UTC, aprokop commented
> We are now getting error messages like

These are the exact messages `ArborX` is getting after that cursed Windows image update.

2024-06-12 19:38 UTC, aprokop commented
`actions/runners` pushed `20240610.1` yesterday. Just need to wait until it deploys.

2024-06-12 20:10 UTC, masterleinad commented
> `actions/runner-images` pushed `20240610.1` yesterday. Just need to wait until it deploys.

It's already using that.
```
Runner Image
  Image: windows-2022
  Version: 20240610.1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240610.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240610.1
```

2024-06-12 20:14 UTC, aprokop commented
> It's already using that.

Well, back to the drawing board then.

2024-06-12 20:28 UTC, crtrott commented
:-(

2024-06-13 17:12 UTC, crtrott approved these changes

2024-06-13 17:15 UTC, crtrott requested changes
The change to TestMDSpanConversion needs to be undone or?

2024-06-13 17:15 UTC, crtrott commented on containers/src/Kokkos_OffsetView.hpp
> +    }
This is anyway a positive change.

2024-06-13 17:23 UTC, masterleinad commented
> The change to TestMDSpanConversion needs to be undone or?

Just removed that change.

2024-06-13 17:24 UTC, crtrott approved these changes

2024-06-13 18:15 UTC, aprokop approved these changes
lgtm

2024-06-13 19:21 UTC, crtrott approved these changes

2024-06-13 20:05 UTC, merged