Make struct "ChunkSize" constructor explicit to avoid implicit construction in RangePolicy
kokkos/kokkos pull request #7151
Opened 2024-07-23 19:21 UTC by tcclevenger

Release 4.3 unintentionally introduced the ability for RangePolicy to take as it's final argument any type convertible to `ChunkSize` and implicitly construct a `ChunkSize` object for the input. Remove that by making the `ChunkSize(int)` constructor explicit.

2024-07-23 19:23 UTC, tcclevenger commented
@dalg24 I'm trying to find a clean way to deprecate the old behavior. Is this necessary? I'm guessing in a single release cycle not too high of a chance that it is being used unintentionally.

2024-07-23 19:33 UTC, dalg24 commented
When I said "investigate" in https://github.com/kokkos/kokkos/issues/7142#issuecomment-2233767695, I meant search downstream (Trilinos?) whether code breaks, since as Nevin pointed out, it is a breaking change even though we never intended to let someone construct `RangePolicy([exec,] (integral)begin, (integral)end, (integral)chunk_size)`.
Considering that we only accidentally enabled that in 4.3, usage should be limited.
A quick search in Trilinos yields
```
packages/stokhos/src/sacado/kokkos/Stokhos_Tpetra_Utilities.hpp:343:      const size_t ChunkSize = 16;
packages/stokhos/src/sacado/kokkos/Stokhos_Tpetra_Utilities.hpp:344:      const size_t M = (m+ChunkSize-1)/ChunkSize;
packages/stokhos/src/sacado/kokkos/Stokhos_Tpetra_Utilities.hpp:346:      Policy policy(M,ChunkSize,ChunkSize);
```
But interestingly, this code was committed in 2018 which means we need to find out if that code was actually built and if so why it worked(?)

2024-07-23 19:40 UTC, dalg24 commented
If we decide (I expect you will make recommendations) we need to go through deprecations, we could do something along these lines https://godbolt.org/z/6TWrfx78a

2024-07-23 20:22 UTC, tcclevenger commented
In those Trilinos files, the `Policy` is a `TeamPolicy`, it is just a coincidence that "chunk size" is used as a variable name. I'll do a little more searching in Trilinos.

2024-07-23 20:46 UTC, dalg24 commented
> In those Trilinos files, the `Policy` is a `TeamPolicy`, it is just a coincidence that "chunk size" is used as a variable name. I'll do a little more searching in Trilinos.

That makes more sense.  Thanks.

2024-07-23 21:03 UTC, dalg24 commented
> If we decide (I expect you will make recommendations) we need to go through deprecations, we could do something along these lines https://godbolt.org/z/6TWrfx78a

I just realized this won't work. `ChunkSize cs{1};` will be ambiguous.

2024-07-23 21:04 UTC, tcclevenger commented
Yeah, I'm testing now we need something different.

2024-07-23 22:27 UTC, masterleinad approved these changes
We'll need to update the documentation accordingly. 
I doubt that anyone noticed any difference but I think it's fair to make the constructor explicit either way.

2024-07-23 22:50 UTC, nliber approved these changes
So, I tried the equivalent of this, but the RangePolicy constructor would now implicitly call the explicit ChunkSize constructor.  I don't know why (both under clang 18.1 and gcc 14.1).

2024-07-23 22:50 UTC, nliber commented on core/src/Kokkos_ExecPolicy.hpp
> +  template <typename T = void>
I didn't know that would work...

2024-07-23 23:02 UTC, dalg24 requested changes
Add a compile time test that check that when deprecated code is disabled, one cannot build a RangePolicy with a trailing integral argument

2024-07-24 15:34 UTC, nmm0 approved these changes
Thanks for doing this, implicit conversions are pretty unfortunate here

2024-07-24 15:40 UTC, masterleinad approved these changes

2024-07-24 15:56 UTC, merged

2024-07-24 15:56 UTC, dalg24 commented
Please make sure you list it under "incompatibilities" in the change log