Improve GH action to produce release artifacts
kokkos/kokkos pull request #7231
Opened 2024-08-16 15:48 UTC by dalg24

* Generate the `kokkos-4.X.YZ-SHA-256.txt` hashes
* Consolidate upload and download steps

The maintainer is only left with certifying the cryptographic hashes.
```
curl -sL https://github.com/kokkos/kokkos/releases/download/4.X.YZ/kokkos-4.X.YZ.zip -o kokkos-4.X.YZ.zip
curl -sL https://github.com/kokkos/kokkos/releases/download/4.X.YZ/kokkos-4.X.YZ.tar.gz -o kokkos-4.X.YZ.tar.gz
curl -sL https://github.com/kokkos/kokkos/releases/download/4.X.YZ/kokkos-4.X.YZ-SHA-256.txt -o kokkos-4.X.YZ-SHA-256.txt
curl -sL https://github.com/kokkos/kokkos/releases/download/4.X.YZ/kokkos-4.X.YZ.intoto.jsonl -o kokkos-4.X.YZ.intoto.jsonl
grep kokkos-4.X.YZ.tar.gz kokkos-4.X.YZ-SHA-256.txt | shasum -c
grep kokkos-4.X.YZ.zip kokkos-4.X.YZ-SHA-256.txt | shasum -c
slsa-verifier verify-artifact kokkos-4.X.YZ.tar.gz --provenance-path kokkos-4.X.YZ.intoto.jsonl --source-uri github.com/kokkos/kokkos --source-tag 4.X.YZ
slsa-verifier verify-artifact kokkos-4.X.YZ.zip --provenance-path kokkos-4.X.YZ.intoto.jsonl --source-uri github.com/kokkos/kokkos --source-tag 4.X.YZ
```
Then unarchive both the zip and tar.gz and diff it with your local copy before certifying and uploading the signature.

2024-08-16 16:21 UTC, dalg24 commented
(in case anyone cares, tested here https://github.com/dalg24/kokkos/releases/tag/5.0.02)

2024-08-19 01:41 UTC, dalg24 commented on .github/workflows/releases.yml
> +          git archive --prefix=kokkos-${{ github.ref_name }}/ -o kokkos-${{ github.ref_name }}.tar.gz HEAD
Fixes #7232

2024-08-19 13:28 UTC, lucbv requested changes
See my comment to remove a line when generating the sha256s, also why do you use grep in the verification step? I believe if you just do `shasum -c mycheckfile-SHA256.txt` will work just fine?

2024-08-19 13:52 UTC, dalg24 commented on .github/workflows/releases.yml
> +          sha256sum kokkos-${{ github.ref_name }}.zip > kokkos-${{ github.ref_name }}-SHA-256.txt
Done

2024-08-19 13:56 UTC, masterleinad approved these changes

2024-08-19 13:56 UTC, masterleinad commented on .github/workflows/releases.yml
> +          sha256sum kokkos-${{ github.ref_name }}.zip  kokkos-${{ github.ref_name }}.tar.gz > kokkos-${{ github.ref_name }}-SHA-256.txt
```suggestion
          sha256sum kokkos-${{ github.ref_name }}.zip kokkos-${{ github.ref_name }}.tar.gz > kokkos-${{ github.ref_name }}-SHA-256.txt
```

2024-08-19 13:59 UTC, dalg24 commented on .github/workflows/releases.yml
> +          sha256sum kokkos-${{ github.ref_name }}.zip  kokkos-${{ github.ref_name }}.tar.gz > kokkos-${{ github.ref_name }}-SHA-256.txt
Thanks.  Amended to the last commit

2024-08-19 14:06 UTC, lucbv commented
I see your point, I guess in our case I assumed we want know if one of them is not downloaded for some reason but for users it makes sense to check individually.

2024-08-19 14:35 UTC, dalg24 commented
> I see your point, I guess in our case I assumed we want know if one of them is not downloaded for some reason but for users it makes sense to check individually.

Didn't realize you were referring to maintainer instructions I wrote in the description and I agree with you in that case `grep` is unnecessary.

2024-08-19 17:59 UTC, dalg24 commented
NVC++ segfault and OpenMPTarget runtime failures are clearly unrelated.

2024-08-19 18:00 UTC, merged