Restrict OpenMP tests for OMP_NUM_THREADS detected at initialization
kokkos/kokkos pull request #7349
Opened 2024-09-17 20:07 UTC by masterleinad

Fixes https://github.com/kokkos/kokkos/issues/7302#issuecomment-2349285849.

It's not quite clear why `exec_space_thread_safety_team_policy` and `exec_space_thread_safety_team_policy` also need `Kokkos` to be configure with at least two threads.

2024-09-18 20:59 UTC, crtrott approved these changes
Fine for now: though we should figure out WHY it does need multiple threads when partitioning. Semantically from the Kokkos perspective it should work without, but we may do something like omp_set_num_threads(0) if the numbers don't work out. @masterleinad can you open an issue for that?

2024-09-18 21:28 UTC, masterleinad commented
> though we should figure out WHY it does need multiple threads when partitioning.

What else would we do if we can't assign any positive of threads to a execution space instance? According to https://www.openmp.org/spec-html/5.0/openmpsu110.html, the behavior for `omp_set_num_threads(0)` is implementation-defined.

2024-09-19 14:36 UTC, masterleinad commented
> @masterleinad can you open an issue for that?

See #7357.

2024-09-23 15:58 UTC, dalg24 requested changes
I do not understand why the Graph tests require more than 1 omp thread to execute.

2024-09-23 16:12 UTC, masterleinad commented
> I do not understand why the Graph tests require more than 1 omp thread to execute.

We want ti use multiple independent execution space instances and we are using `partition_space` with an `OpenMP` execution space instance to do that. That means that we distribute the number of threads for the input instance to between the output execution space instances and each of them most have at least one thread assigned which means the input execution space instance must have at least as many execution space instances assigned as the number of execution space instances we wan to create.

2024-09-23 19:49 UTC, dalg24 commented
How isn't it just a bug in `create_OpenMP_instances()` rather than a property of that test?

2024-09-23 20:07 UTC, dalg24 reviewed
On 2nd thought I don't see why we need the skip in the other tests either considering that we do
https://github.com/kokkos/kokkos/blob/94d211a617ea655e774d3460c1bf2ee86431b2f6/core/unit_test/TestExecSpacePartitioning.hpp#L87-L91

And to be clear I am saying that the current implementation of `partition_space()` for OpenMP is wrong, that even if you have omp num threads equal to 1, partitioning the default execution space instance into multiple instances should work and that all created instances should also have 1 thread.

2024-09-23 20:44 UTC, crtrott commented
Just to make that absolutely clear: I was ok with disabling the test until we have fixed partition space. Yes the threaded test which sets omp_num_threads(2) does need explicitly skip out (though we could check something like omp_max_threads() or whatever it's called instead of concurrency), but the ones which just fail because of partition space: for those we should fix partition space. As a stop gap I am ok with merging a test disabling.

2024-09-23 20:44 UTC, dalg24 commented on core/unit_test/TestExecSpacePartitioning.hpp
> +#endif
```suggestion
  if (omp_get_max_threads() == 1)
    GTEST_SKIP() << "insufficient number of supported concurrent threads";
```
Same comment everywhere in this file and the thread safety one

2024-09-24 02:40 UTC, dalg24 approved these changes
Sure

2024-09-24 02:40 UTC, dalg24 commented on core/unit_test/TestExecSpacePartitioning.hpp
> +  if (omp_get_max_threads() == 1)
```suggestion
  if (omp_get_max_threads() < 2)
```

2024-09-24 02:40 UTC, dalg24 commented on core/unit_test/TestExecSpaceThreadSafety.hpp
> +  if (omp_get_max_threads() == 1)
```suggestion
  if (omp_get_max_threads() < 2)
```

2024-09-24 02:40 UTC, dalg24 commented on core/unit_test/TestGraph.hpp
> +  if (ex.concurrency() == 1)
```suggestion
  if (ex.concurrency() < 2)
```

2024-09-25 13:06 UTC, masterleinad commented
Only `Stage 'CUDA-12.2-NVHPC-AS-HOST-COMPILER'` is failing with an unrelated segmentation fault in the compiler.

2024-09-25 15:15 UTC, merged