Abort instead of throwing on precondition violation in `OffsetView`
kokkos/kokkos pull request #7374
Opened 2024-09-25 03:01 UTC by dalg24

Working towards #7037 
Affects error reporting on invalid number of begin/end arguments on unmanaged OffsetView constructor and on out of bounds accesses.
The regexes are painful but they did catch a misprint in the error.  Let me know if you want to simplify or even ignore the messages.

2024-09-25 12:43 UTC, Rombur commented
Retest this please

2024-09-25 12:45 UTC, Rombur approved these changes

2024-09-25 15:50 UTC, cwpearson approved these changes

2024-09-25 18:17 UTC, crtrott requested changes
Test doesn't work on Windows it seems.

2024-09-27 02:53 UTC, dalg24 commented
```
[----------] 1 test from serial_DeathTest
[ RUN      ] serial_DeathTest.offsetview_unmanaged_construction
C:\projects\source\containers\unit_tests\TestOffsetView.hpp(356): error: Death test: offset_view_type(&s, {0}, {-1})
    Result: died but not with expected error.
  Expected: contains regular expression "Kokkos::Experimental::OffsetView ERROR: for unmanaged OffsetView.*must be non-negative"
Actual msg:
[  DEATH   ] Kokkos::Experimental::OffsetView ERROR: for unmanaged OffsetView
[  DEATH   ] (ends[0] (-1) - begins[0] (0)) must be non-negative
[  DEATH   ] 
[  DEATH   ] Traceback functionality not available
[  DEATH   ] 
[  FAILED  ] serial_DeathTest.offsetview_unmanaged_construction (21 ms)
[----------] 1 test from serial_DeathTest (21 ms total)
[----------] 64 tests from serial
```
Sounds like on Windows there is a different syntax where `.` does not match `\n`.  Great...

2024-09-27 13:26 UTC, merged