Use std::thread::hardware_concurrency as default for the Threads backend
kokkos/kokkos pull request #7402
Opened 2024-10-04 14:26 UTC by masterleinad

Related to https://github.com/kokkos/kokkos/issues/7090. It's strane that the `Threads` backend only uses one thread by default whereas we autodetect the number of hardware concurrent threads for other host parallel backends.

2024-10-04 16:58 UTC, crtrott commented
std::thread::hardware_conccurency is bad I think. I thought we investigated this before. I.e. it did not seem to take into account stuff like process masks?

2024-10-04 17:07 UTC, masterleinad commented
> std::thread::hardware_conccurency is bad I think. I thought we investigated this before. I.e. it did not seem to take into account stuff like process masks?

That's what we are using for `OpenACC` as concurrency (if targeting host) and for `cores per node` when detecting MPI over-subscription with `Threads` and `OpenMP`. It's not necessarily a very good value but better than just 1. When configuring with hwloc, we take more information into account.

2024-10-04 17:13 UTC, crtrott commented
Ok I guess I remember wrong.

2024-10-07 19:38 UTC, janciesko commented
I don't have a critical dependency on the default behavior w/o hwloc. The change looks good to me and seems consistent with other backends.

2024-10-07 20:31 UTC, janciesko approved these changes

2024-10-07 22:52 UTC, dalg24 requested changes
This has been discussed in the past and we had agreed that the status quo was better than wildly oversubscribing nodes with the default setting.

We should consider revisiting/cleaning up our hwloc wrappers and potentially bundling it by default with Kokkos.

2024-10-08 00:36 UTC, masterleinad commented
> This has been discussed in the past and we had agreed that the status quo was better than wildly oversubscribing nodes with the default setting.

We do have warnings for oversubscription with MPI and they use `std::thread::hardware_concurrency` as well, see https://github.com/kokkos/kokkos/blob/4e88587265240078b2d6d94261d118e7a4a15cea/core/src/Threads/Kokkos_Threads_Instance.cpp#L600-L615.

2024-10-08 01:50 UTC, dalg24 commented
> > This has been discussed in the past and we had agreed that the status quo was better than wildly oversubscribing nodes with the default setting.
> 
> We do have warnings for oversubscription with MPI and they use `std::thread::hardware_concurrency` as well, see

Sure.  We had it back then too.
To be clear I am not saying this can never change, just that there we are relitigating something we looked at in the past and that there is no new information being brought up so far.

2024-10-14 17:54 UTC, janciesko commented
Given that `std::thread::hardware_concurrency` hints on how many threads can be running in parallel at any given moment in time (vs. how many can be created), I wonder if a heuristic that adjusts that default value relative to reported ranks might be better?

2024-10-14 18:31 UTC, masterleinad commented
> Given that `std::thread::hardware_concurrency` hints on how many threads can be running in parallel at any given moment in time (vs. how many can be created), I wonder if a heuristic that adjusts that default value relative to reported ranks might be better?

Feel free to suggest something better.

2024-10-21 15:47 UTC, closed without merging