Introduce index_type and standardize size_type across Kokkos backends
kokkos/kokkos pull request #7441
Opened 2024-10-14 16:10 UTC by janciesko

This PR introduces a signed `index_type` for each memory and execution space and standardizes `size_type` as unsigned across all Kokkos backends. This aligns Kokkos with the mdspan model where `index_type` is signed and `size_type` is unsigned.

### Motivation
- **Signed indexing**: Signed indices are safer for arithmetic (e.g., negative ranges) and avoid undefined behavior in overflow cases.
- **Consistency**: Different backends previously used different index/size semantics; this makes them uniform.
- **mdspan compatibility**: `std::mdspan` uses `index_type` (signed) and `size_type` (unsigned); Kokkos Views should mirror this.

### Changes
Memory spaces
- Add `index_type = std::make_signed_t<size_type>` to all memory spaces:
  - Cuda: `CudaSpace`, `CudaUVMSpace`, `CudaHostPinnedSpace`
  - HIP: `HIPSpace`, `HIPHostPinnedSpace`, `HIPManagedSpace`
  - Host: `HostSpace`, `AnonymousSpace`
  - OpenACC: `OpenACCSpace`
  - SYCL: `SYCLDeviceUSMSpace`, `SYCLSharedUSMSpace`, `SYCLHostUSMSpace`
Execution spaces
- Propagate `index_type` from memory space to execution spaces (Cuda, HIP, HPX, OpenACC, OpenMP, SYCL, Serial, Threads).
Policies
- Default policy `index_type` is now `execution_space::index_type` instead of `execution_space::size_type`.
- Improved overflow handling in `RangePolicy` for signed index types.
Views and CRS
- `BasicView`: Use `mdspan_type::index_type` for `index_type`.
- `ViewTraits`: Add `index_type`.
- `Crs`: Use `index_type` in transpose and count/fill utilities.

2024-12-02 18:21 UTC, janciesko commented
Retest this please.

2025-10-13 17:50 UTC, dalg24 submitted a review, later dismissed
We agreed `index_type` was going to be signed, defined as `std::make_signed_t<size_type>;`

2025-10-13 17:50 UTC, dalg24 commented on core/src/HIP/Kokkos_HIP_Space.hpp
> +  using size_type       = index_type;
This one is wrong
```suggestion
  using size_type       = unsigned int;
  using index_type      = std::make_signed_t<size_type>;
```

2025-10-13 17:50 UTC, dalg24 commented on core/src/Kokkos_AnonymousSpace.hpp
> +  using index_type      = size_type;
```suggestion
  using index_type      = std::make_signed_t<size_type>;
```

2025-10-13 17:53 UTC, dalg24 commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
Why do we want it in the View traits?
Why is it part of this PR?

2025-10-13 17:53 UTC, dalg24 commented on core/src/OpenACC/Kokkos_OpenACCSpace.hpp
> +  using index_type = size_type;
```suggestion
  using index_type = std::make_signed_t<size_type>;
```

2025-10-13 17:53 UTC, dalg24 commented on core/src/Kokkos_HostSpace.hpp
> +  using index_type   = size_type;
```suggestion
  using index_type   = std::make_signed_t<size_type>;
```

2025-10-13 19:05 UTC, cwpearson commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
it might be surprising for `size_type` to exist and `index_type` to not exist if they're side-by-side everywhere else.

2025-10-13 19:06 UTC, cwpearson reviewed
Looks like we refer to `size_type` in the docs as what we now mean by `index_type`?

https://github.com/kokkos/kokkos-core-wiki/blob/08d3bfd041455efa4154290a578a707f13e15ae9/docs/source/API/core/view/view.rst?plain=1#L191-L193

(that's not the only place, e.g. DynRankView)

2025-10-13 20:17 UTC, masterleinad commented
> Looks like we refer to `size_type` in the docs as what we now mean by `index_type`?

Yes, the idea is to replace `size_type` with `index_type` and possibly deprecate `size_type`.

2025-10-13 22:12 UTC, janciesko commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
We don't have a use for it, @dalg24 is right, rolled back change.

2025-10-22 22:38 UTC, janciesko commented
@masterleinad, I've added two separate tests but simplified the `check_conversion_safety`.

2025-10-23 20:59 UTC, masterleinad commented
> @masterleinad, I've added two separate tests but simplified the `check_conversion_safety`.

This is failing on pretty much every single CI build. Does the tests pass for you locally?

2025-10-30 18:57 UTC, janciesko commented
Fixing

2026-03-02 22:20 UTC, masterleinad commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> -      Kokkos::RangePolicy<ExecutionSpace, Kokkos::IndexType<size_t>>;
Why did you change?

2026-03-02 22:20 UTC, masterleinad commented on core/src/traits/Kokkos_IndexTypeTrait.hpp
> -                             typename base_t::schedule_type>>{};
That was just wrong it seems.

2026-03-03 12:58 UTC, dalg24 commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +  using policy_t         = Kokkos::RangePolicy<ExecutionSpace>;
This would break if we changed the definition of `HostSpace::index_type`.
Any particular reason to touch this code?

2026-03-03 12:58 UTC, dalg24 commented on core/src/View/Kokkos_BasicView.hpp
> +  using index_type       = typename mdspan_type::index_type;
Why does that change belong to this PR?

2026-03-03 12:58 UTC, dalg24 commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, index_type(0), index_type(n));
The original code was explicitly requesting 64-bit integers.
Why are we changing it to something that is backend-specific?
Isn't going to fall over say with a 9GB allocation of some 4-byte non-trivially constructible user-defined type (e.g. `n > INT_MAX` on CUDA or HIP).

2026-03-03 12:58 UTC, dalg24 commented on core/src/View/Kokkos_ViewAlloc.hpp
> +      operator()(ConstructTag, const ExecSpace::index_type i) const {
It looks like we were explicitly requesting 64-bit integers to index into that array we are allocating.

2026-03-03 12:58 UTC, dalg24 commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
I am confused.  What was rolled back?  Why is this change still part of this PR?

2026-03-03 12:58 UTC, dalg24 commented on core/src/Kokkos_ExecPolicy.hpp
> +        }
Was there a gap in our RangePolicy constructor testing?

2026-03-03 12:58 UTC, dalg24 commented on core/src/traits/Kokkos_IndexTypeTrait.hpp
> +                             typename base_t::index_type>>{};
So if I understand correctly, what was wrong was the error message we would produce, if specifying twice the integer type to use with the policy (via template arguments)
https://godbolt.org/z/raGMTsxrd

2026-03-03 18:48 UTC, janciesko commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +  using policy_t         = Kokkos::RangePolicy<ExecutionSpace>;
It would, hence the index type is part of the exec space. We cannot arbitrarily change that.

2026-03-03 18:57 UTC, dalg24 commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +  using policy_t         = Kokkos::RangePolicy<ExecutionSpace>;
I don't understand the answer.  I am saying was there a particular harm in being explicit?  Is it better to have that code work implicitly because the default index type is (hopefully) going to be large enough.

2026-03-03 19:00 UTC, janciesko commented on core/src/Kokkos_ExecPolicy.hpp
> +        }
See comment in-line

2026-03-03 19:05 UTC, janciesko commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +  using policy_t         = Kokkos::RangePolicy<ExecutionSpace>;
"Being explicit" and "index type is (hopefully) going to be large enough" are good considerations but I think they could be addressed when defining the default `index_type` (which could be size_t) for that exec space.

2026-03-03 19:09 UTC, janciesko commented on core/src/View/Kokkos_ViewAlloc.hpp
> +      operator()(ConstructTag, const ExecSpace::index_type i) const {
For consistency we should probably use index type here.

2026-03-03 19:11 UTC, janciesko commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, index_type(0), index_type(n));
This is an interesting case. Looking for more input if we should hard-code such loops to use 64 bits indices or infer from index_type.

2026-03-03 19:11 UTC, masterleinad commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +  using policy_t         = Kokkos::RangePolicy<ExecutionSpace>;
No, it's not. We explicitly want the index type here tp be `size_t` since that's the maximum range of the allocation. `IndexType` neesd to be kernel-specific (with a default as `ExecutionSpace::index_type`).

2026-03-03 19:12 UTC, janciesko commented on core/src/traits/Kokkos_IndexTypeTrait.hpp
> -                             typename base_t::schedule_type>>{};
I think so

2026-03-03 19:12 UTC, masterleinad commented on core/src/View/Kokkos_ViewAlloc.hpp
> +      operator()(ConstructTag, const ExecSpace::index_type i) const {
You want to use the `index_type` of the policy here but since that isn't available we need tp be explicit and use `size_t`.

2026-03-03 19:15 UTC, janciesko commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +  using policy_t         = Kokkos::RangePolicy<ExecutionSpace>;
aah, I mixed up the words. Yes, `size_type` here which is potentially larger than index_type. Good point, thanks Daniel.

2026-03-03 19:23 UTC, dalg24 commented on core/src/Kokkos_ExecPolicy.hpp
> +        }
I can see the comment, I am asking why we did not realize this before and whever we need to update `core/unit_test/TestRangePolicyConstructors.hpp`

2026-03-03 19:23 UTC, janciesko commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +  using policy_t         = Kokkos::RangePolicy<ExecutionSpace>;
Probably not even `size_type` but `size_t`.

2026-03-03 19:32 UTC, janciesko commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
~~Forgot about this and put it back. Reverted.~~

`[‎core/src/Kokkos_Crs.hpp]` seems to have a dependency on `traits::index_type` now.

2026-03-03 19:56 UTC, janciesko commented on core/src/Kokkos_ExecPolicy.hpp
> +        }
We did not realize this before as our tests tested for positive (or zero) indices only. Testing with negative indices produces those warnings now. The new tests are in `TestRangePolicyConstructors.hpp`.

2026-03-04 15:19 UTC, masterleinad commented on core/src/traits/Kokkos_IndexTypeTrait.hpp
> +                             typename base_t::index_type>>{};
Could also be in a separate pull request.

2026-03-04 19:50 UTC, janciesko commented on core/src/View/Kokkos_ViewAlloc.hpp
> +      operator()(ConstructTag, const ExecSpace::index_type i) const {
Agreed, reverted, thanks for the rational.

2026-03-04 19:52 UTC, janciesko commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, index_type(0), index_type(n));
Same rational applies here I think, thanks for pointing it out Damien. Still we likely want to use `size_t` as the index type.

2026-03-04 19:59 UTC, masterleinad commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, index_type(0), index_type(n));
Generally, you should probaby leave `size_t` alone (if it's not the alias declaration `using size_type = size_t`).

2026-03-18 19:56 UTC, janciesko commented on core/src/View/Kokkos_BasicView.hpp
> +  using index_type       = typename mdspan_type::index_type;
It seems reasonable to 
`using index_type = typename mdspan_type::size_type;` -> 
`using index_type = typename mdspan_type::index_type;`

2026-04-02 21:47 UTC, crtrott requested changes
Couple comments to be addressed. But there is also one bigger one: we are changing the sign of RangePolicy begin/end. This might be a bit worrisome, and will pop up warnings in downstream code everywhere. On the other hand I am also feeling really uncomfortable with negative begin values not working by default. Thoughts?

2026-04-02 21:47 UTC, crtrott commented on core/src/Cuda/Kokkos_CudaSpace.hpp
> +  using index_type      = std::make_signed_t<size_type>;
Should we turn the logic around? mdspan defines index_type and then makes size_type the unsigned version. I do agree that we should have a default index type for the execution spaces which is signed, in order to support negative indices.

2026-04-02 21:47 UTC, crtrott commented on core/src/Cuda/Kokkos_CudaSpace.hpp
> +  using index_type      = std::make_signed_t<size_type>;
Note this is a question, not a mandate to change. Ending up with `unsigned int` / `int` respectively for our GPU spaces and the 64bit variants for host is fine with me.

2026-04-02 21:47 UTC, crtrott commented on core/src/View/Kokkos_BasicView.hpp
> +  using index_type       = typename mdspan_type::index_type;
I think this is fine, right now it's anyway hardcoded to size_t and it falls into the cleanup of index_type being consistently used.

2026-04-02 21:47 UTC, crtrott commented on core/src/View/Kokkos_ViewAlloc.hpp
> +      operator()(ConstructTag, const ExecSpace::index_type i) const {
It's not yet reverted is it? And the rational for using 64bit indexing in all these guys is that we are instantiating these kernels to loop over the entries of a View during initialization and destruction. This thus needs to cover the range of the index_type we are using in the View, which currently is actually 64bit. And it needs to be to cover more than 2B elements. Since we are not passing the View in here lets leave these alone for now, and rework this when we actually can change the View index_type, thus we could know here at compile time that we wouldn't have more than 2B iterations.

2026-04-02 21:47 UTC, crtrott commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, index_type(0), index_type(n));
Same needs to be reverted since we may have allocations of more than 2B elements.

2026-04-02 21:47 UTC, crtrott commented on core/src/View/Kokkos_ViewLegacy.hpp
> +  using index_type = typename traits::index_type;
Let's leave this guy alone.

2026-04-02 21:47 UTC, crtrott commented on core/src/Kokkos_ExecPolicy.hpp
> +            // conversion ‘long int’ to ‘int’ changes value
```suggestion
            // conversion ‘unsigned int’ to ‘int’ changes value
```

2026-04-02 21:47 UTC, crtrott commented on core/src/Kokkos_ExecPolicy.hpp
> +            // conversion ‘long int’ to ‘int’ changes value
We are in the IndexType is unsigned case right now.

2026-04-06 17:10 UTC, janciesko commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, index_type(0), index_type(n));
Agreed. Reverted in: https://github.com/kokkos/kokkos/pull/7441/changes/53b132f5df4492a1456115bc5ea74121c1734ccb

2026-04-06 17:50 UTC, masterleinad commented on core/unit_test/TestRangePolicyConstructors.hpp
> +    ASSERT_DEATH({ (void)DefaultPolicy(0, test_val); },
`DefaultPolicy` isn't defined.

2026-04-06 18:22 UTC, masterleinad commented
> But there is also one bigger one: we are changing the sign of RangePolicy begin/end. This might be a bit worrisome, and will pop up warnings in downstream code everywhere. On the other hand I am also feeling really uncomfortable with negative begin values not working by default. Thoughts?

Since `index_type` didn't exist before, I don't think (`-Wsign-compare`-type) warnings are a concern downstream generally. The change that appears in user programs is assgnment between values of different signedness but I'm not aware that the major compilers generally warn about that. Compiling with `-Wsign-conversion` in `Kokkos` would already give a lot of extra warnings.

For  the `SYCL` backend, we had used `size_type=int` and that triggered warnings in user codes whenever `ExecutionSpace::size_type` was explicitly used for a loop variable (or similar). IIn https://github.com/kokkos/kokkos/pull/8542, we changed that type to be unsigned for consistency with other backends but I haven't heard anyone complaining about more warnings.

2026-04-06 18:35 UTC, masterleinad submitted a review, later dismissed

2026-04-06 18:35 UTC, masterleinad commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +                       [=](const index_t i) { dst_p[i] = z_u64; });
This still wrong. There are no changes necessary in this file.

2026-04-06 18:35 UTC, masterleinad commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, size_t(0), n);
Why did you change?

2026-04-06 18:35 UTC, masterleinad commented on core/unit_test/view/TestBasicView.hpp
> +      0, static_cast<index_type>(extents.extent(0))};
Why did you change?

2026-04-06 19:37 UTC, janciesko commented on core/src/impl/Kokkos_HostSpace_deepcopy.cpp
> +                       [=](const index_t i) { dst_p[i] = z_u64; });
Oversight probably, thanks! Rolled back.

2026-04-06 19:39 UTC, janciesko commented on core/unit_test/view/TestBasicView.hpp
> +      0, static_cast<index_type>(extents.extent(0))};
This is unnecessary. Rolled back.

2026-04-06 19:39 UTC, janciesko commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, size_t(0), n);
This seems like an oversight in the original code.

2026-04-06 19:49 UTC, masterleinad commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, size_t(0), n);
I'd be suprised if you can create an allocation larger than `std::numeric_limits<std::int64_t>::max()`. 🙂 

Note that `size_t` isn't necessarily a 64-bit type so the new comment seems to apply better to the old code. If you keep the change here, I would remove the comment.

2026-04-06 20:49 UTC, dalg24 commented on core/src/Cuda/Kokkos_CudaSpace.hpp
> +  using index_type      = std::make_signed_t<size_type>;
You mean this
```suggestion
  using index_type      = int;
  using size_type       = std::make_unsigned_t<index_type>;
```

Fine by me.

2026-04-06 21:35 UTC, dalg24 commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
Why are the Crs changes part of this PR in the first place?

2026-04-06 21:37 UTC, dalg24 commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, size_t(0), n);
I agree with Daniel, I don't see any good reason for this change.
On second thought I don't really care to revert.
I don't find the comment particularly useful.

2026-04-06 21:57 UTC, dalg24 commented on core/unit_test/TestTeamPolicyCTAD.cpp
> +    using index_type      = std::make_signed_t<size_type>;
```suggestion
    using index_type      = int;
```

2026-04-06 21:57 UTC, dalg24 commented on core/unit_test/TestRangePolicyCTAD.cpp
> +    using index_type      = std::make_signed_t<size_type>;
```suggestion
    using index_type      = int;
```

2026-04-06 21:57 UTC, dalg24 commented on core/unit_test/TestMDRangePolicyCTAD.cpp
> +    using index_type      = std::make_signed_t<size_type>;
```suggestion
    using index_type      = int;
```

2026-04-06 22:23 UTC, dalg24 reviewed
Don't forget to also update the NextSilicon backend

2026-04-06 22:23 UTC, dalg24 commented on core/unit_test/TestRange.hpp
> +            (-1) * offset, N - offset),
```suggestion
            -offset, N - offset),
```

2026-04-06 22:23 UTC, dalg24 commented on core/unit_test/TestRangePolicyConstructors.hpp
> +  Index work_begin = -5;
Why change this unit test?

2026-04-07 19:59 UTC, dalg24 commented on core/unit_test/TestTeamPolicyCTAD.cpp
>      using size_type       = size_t;
```suggestion
```

2026-04-07 19:59 UTC, dalg24 commented on core/unit_test/TestRangePolicyCTAD.cpp
>      using size_type       = size_t;
```suggestion
```

2026-04-07 19:59 UTC, dalg24 commented on core/unit_test/TestMDRangePolicyCTAD.cpp
>      using size_type       = size_t;
```suggestion
```

2026-04-07 20:00 UTC, janciesko commented on core/unit_test/TestRangePolicyConstructors.hpp
> +  Index work_begin = -5;
I think we can reuse this test, just extending the ranges.

2026-04-07 20:27 UTC, dalg24 commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
Ping

2026-04-07 20:34 UTC, ldh4 commented on core/src/Kokkos_ExecPolicy.hpp
> +            if constexpr (sizeof(member_type) <= sizeof(IndexType))
If this produced an overflow warning when `IndexType` is narrower than `member_type`, wouldn't there be a same warning produced from L270, which does the same casting check?

Also, I'm not sure if relying on sizeof is safe, since IndexType could be any user defined type (could be implicitly convertible to and from `member_type` but may not necessarily an arithmetic type)

2026-04-07 20:34 UTC, ldh4 commented on core/src/Kokkos_ExecPolicy.hpp
> +        }
I may be little confused on the provided comments,
but because of this condition in the check:
```
        if constexpr (std::is_signed_v<IndexType> !=
                      std::is_signed_v<member_type>) {
```
this portion of check is for when signedness of `IndexType` and `member_type` don't match (except when IndexType is a user-defined type)
The unit tests you added in `TestRangePolicyConstructors.hpp` seems to be only signed (`long long`) to signed (`int`) conversion.

2026-04-08 18:24 UTC, janciesko commented on core/src/Kokkos_ExecPolicy.hpp
> +            if constexpr (sizeof(member_type) <= sizeof(IndexType))
The `sizeof` split is only trying to avoid the specific diagnostic error you get from  
`bound > static_cast<IndexType>(std::numeric_limits<member_type>::max())` when `IndexType` is narrower than `member_type` (e.g. `member_type = unsigned long long`, `IndexType = int`): the cast of `max()` to a narrower signed type is what triggers the “value changes on conversion” style warning. 

The conversion is safe given we're in the `if constexpr (std::is_arithmetic_v<member_type>)`  branch.

2026-04-08 18:29 UTC, janciesko commented on core/src/Kokkos_ExecPolicy.hpp
> +        }
Yes, the `long long` + `RangePolicy<int>` death tests look like “signed to signed”; note that we're testing the round-trip / narrowing path there. We test for the signedness mismatch between the bound type and the policy index type in the `range_policy_implicitly_converted_bounds` tests.

2026-04-08 18:35 UTC, janciesko commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
Hey Damien, CRS uses ViewTraits and RangePolicy with an explicit index type; when the default policy index becomes execution_space::index_type, the CRS helpers should probably use that too.  It is for consistency with the index-type rollout.

2026-04-15 13:08 UTC, dalg24 commented on core/src/View/Kokkos_ViewTraits.hpp
> +  using index_type = typename MemorySpace::index_type;
I do not think that we should handle Crs as part of this PR.
Please withdraw these changes.

2026-04-15 22:54 UTC, ldh4 commented on core/unit_test/TestRangePolicyConstructors.hpp
> +  // ASSERT_DEATH((void)Policy(0, W(&n)), msg);
I would uncomment this and disable the test by prepending the test name with `DISABLED` (`DISABLED_range_policy_round_trip_conversion_fires`).
Or, place an extra `long` var in the struct `W`, and it will trigger the expected abort.

2026-04-15 22:54 UTC, ldh4 commented on core/src/Kokkos_ExecPolicy.hpp
> +            if constexpr (sizeof(member_type) <= sizeof(IndexType))
I get that this is to avoid the overflow warning and that adding this additional constraint doesn't alter the upper bound check.
However, I have a tangential concern on the usage of `sizeof`. This condition is fine when `IndexType` is an arithmetic type but not when `IndexType` is a UDT padded with extra variables.

For instance, in the test that was disabled in this PR `range_policy_round_trip_conversion_fires`, padding the struct `W` with an extra `long` will satisfy the condition `(sizeof(member_type) <= sizeof(IndexType))` even though the actual used index type is `int`. So `sizeof` seems unreliable here when `IndexType` isn't arithmetic.

2026-04-21 17:37 UTC, janciesko commented on core/src/Kokkos_ExecPolicy.hpp
> +            if constexpr (sizeof(member_type) <= sizeof(IndexType))
Aah, yes, that's right, I have not thought that through. The entire block should be replaceable with `std::in_range`.

2026-04-21 17:51 UTC, janciesko commented on core/src/Kokkos_ExecPolicy.hpp
>        if constexpr (std::is_arithmetic_v<member_type> &&
@ldh4 How's this?

2026-04-21 21:26 UTC, ldh4 commented on core/src/Kokkos_ExecPolicy.hpp
>        if constexpr (std::is_arithmetic_v<member_type> &&
Yeah maybe this is how it'll have to be, bypassing this check if `IndexType` is a UDT. I wasn't sure if there's a way to keep the bounds check correct while considering all cases of UDTs.

As for `std::in_range`, I believe it only works for integral types. We could definitely check with `std::in_range` if both `member_type` and `IndexType` are integrals. Otherwise, maybe fallback to the previous implementation (given that both types are still arithmetic types)?

2026-04-22 18:23 UTC, janciesko commented on core/src/Kokkos_ExecPolicy.hpp
>        if constexpr (std::is_arithmetic_v<member_type> &&
`std::in_range` does not buy us anything. Reverted.

2026-04-22 20:51 UTC, ldh4 approved these changes

2026-05-06 20:53 UTC, nmm0 reviewed
First pass, I will take another look tomorrow

2026-05-06 20:53 UTC, nmm0 commented on core/src/OpenACC/Kokkos_OpenACCSpace.hpp
> +  using index_type = std::make_signed_t<size_type>;
I think this is okay, but worth mentioning that this will likely be a signed 64 bit int instead of the other device execution spaces which are signed 32 bit ints

2026-05-06 20:53 UTC, nmm0 commented on core/src/View/Kokkos_ViewAlloc.hpp
> +        Kokkos::RangePolicy<ExecSpace, Kokkos::IndexType<size_t>, Tag>;
This may or may not be 64 bit, I'd rather not driveby change this

2026-05-06 20:53 UTC, nmm0 commented on core/src/Kokkos_ExecPolicy.hpp
> +                    std::is_arithmetic_v<IndexType>) {
If I understand this correctly, and this doesn't have to work on device we may be able to simplify the representability part with https://en.cppreference.com/cpp/utility/in_range

2026-05-08 18:31 UTC, crtrott commented on core/src/View/Kokkos_ViewAlloc.hpp
> +        Kokkos::RangePolicy<ExecSpace, Kokkos::IndexType<size_t>, Tag>;
there is a conversion thing otherwise going on, because the functor called already was using size_t.

2026-05-08 18:31 UTC, crtrott commented on core/src/View/Kokkos_ViewAlloc.hpp
> +    PolicyType policy(space, size_t(0), n);
its fine, only on 32bit machines would it not be 64bit but then we don't need it either.

2026-05-08 18:32 UTC, crtrott approved these changes

2026-05-11 13:49 UTC, crtrott commented
Retest this please.

2026-05-11 20:45 UTC, janciesko commented on core/src/OpenACC/Kokkos_OpenACCSpace.hpp
> +  using index_type = std::make_signed_t<size_type>;
The reduction seems to be broken

2026-05-12 19:27 UTC, janciesko commented on core/src/OpenACC/Kokkos_OpenACCSpace.hpp
> +  using index_type = std::make_signed_t<size_type>;
@nmm0 Should be fixed.

2026-05-12 21:21 UTC, masterleinad commented on core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Range.hpp
> +    std::size_t tStep;
What's going on here?

2026-05-13 18:41 UTC, janciesko commented on core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Range.hpp
> +    std::size_t tStep;
For OpenACC, the reduction was producing wrong results in our unit tests with the defaulted `index_type` which now is a `signed` type. 

It seems that what the compiler produces for those binary operations in that reduction is wrong. Given that `chunk_size` is always positive, I am not sure which particular binary op causes this.

Casting to an unsigned type resolved this issue. This applies only to the OpenACC backend.

2026-05-13 18:58 UTC, masterleinad commented on core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Range.hpp
> +    std::size_t tStep;
@seyonglee Can you provide more insight into this?

2026-05-14 03:52 UTC, seyonglee commented on core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Range.hpp
> +    std::size_t tStep;
I don't know why but sometimes explicit `acc loop seq` directive causes incorrect code generation; deleting them will fix the error.

2026-05-14 21:28 UTC, dalg24 commented on core/src/View/Kokkos_BasicView.hpp
> +  using index_type       = typename mdspan_type::index_type;
Again I do not understand why this change belong here.  Please revert it and propose it as a follow up PR

2026-05-15 16:11 UTC, janciesko commented
I think this is ready to go. @masterleinad, @seyonglee could you finalize the review?

2026-05-15 16:13 UTC, janciesko commented on core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Range.hpp
> +    std::size_t tStep;
This seems to have fixed it. Great to see this collaboration. Thanks again @seyonglee @masterleinad

2026-05-18 14:47 UTC, seyonglee approved these changes

2026-05-20 16:41 UTC, merged